import type { CodeGroup, Code } from "@fms/types"

export const mockCodeGroups: CodeGroup[] = [
  {
    id: "1",
    groupCode: "USER_LEVEL",
    groupName: "사용자 레벨",
    description: "시스템 사용자의 권한 레벨",
    isActive: true,
    sortOrder: 1,
    createdAt: "2024-01-01T00:00:00Z",
    updatedAt: "2024-01-01T00:00:00Z",
    createdBy: "system",
    updatedBy: "system",
    codeCount: 4,
  },
  {
    id: "2",
    groupCode: "EQUIPMENT_TYPE",
    groupName: "설비 유형",
    description: "설비의 분류 유형",
    isActive: true,
    sortOrder: 2,
    createdAt: "2024-01-01T00:00:00Z",
    updatedAt: "2024-01-01T00:00:00Z",
    createdBy: "system",
    updatedBy: "system",
    codeCount: 8,
  },
  {
    id: "3",
    groupCode: "MAINTENANCE_TYPE",
    groupName: "보전 유형",
    description: "보전 작업의 분류",
    isActive: true,
    sortOrder: 3,
    createdAt: "2024-01-01T00:00:00Z",
    updatedAt: "2024-01-01T00:00:00Z",
    createdBy: "system",
    updatedBy: "system",
    codeCount: 6,
  },
  {
    id: "4",
    groupCode: "FAILURE_CAUSE",
    groupName: "고장 원인",
    description: "설비 고장의 원인 분류",
    isActive: true,
    sortOrder: 4,
    createdAt: "2024-01-01T00:00:00Z",
    updatedAt: "2024-01-01T00:00:00Z",
    createdBy: "system",
    updatedBy: "system",
    codeCount: 12,
  },
  {
    id: "5",
    groupCode: "PRIORITY",
    groupName: "우선순위",
    description: "작업 우선순위 분류",
    isActive: true,
    sortOrder: 5,
    createdAt: "2024-01-01T00:00:00Z",
    updatedAt: "2024-01-01T00:00:00Z",
    createdBy: "system",
    updatedBy: "system",
    codeCount: 5,
  },
  {
    id: "6",
    groupCode: "STATUS",
    groupName: "상태",
    description: "공통 상태 코드",
    isActive: false,
    sortOrder: 6,
    createdAt: "2024-01-01T00:00:00Z",
    updatedAt: "2024-01-01T00:00:00Z",
    createdBy: "system",
    updatedBy: "system",
    codeCount: 3,
  },
]

export const mockCodes: Code[] = [
  // 사용자 레벨
  {
    id: "1",
    groupId: "1",
    groupCode: "USER_LEVEL",
    groupName: "사용자 레벨",
    code: "ADMIN",
    name: "관리자",
    description: "시스템 전체 관리 권한",
    value: "admin",
    level: 1,
    sortOrder: 1,
    isActive: true,
    isSystem: true,
    attributes: { color: "#dc2626", icon: "crown" },
    createdAt: "2024-01-01T00:00:00Z",
    updatedAt: "2024-01-01T00:00:00Z",
    createdBy: "system",
    updatedBy: "system",
  },
  {
    id: "2",
    groupId: "1",
    groupCode: "USER_LEVEL",
    groupName: "사용자 레벨",
    code: "MANAGER",
    name: "매니저",
    description: "부서별 관리 권한",
    value: "manager",
    level: 1,
    sortOrder: 2,
    isActive: true,
    isSystem: true,
    attributes: { color: "#2563eb", icon: "shield-check" },
    createdAt: "2024-01-01T00:00:00Z",
    updatedAt: "2024-01-01T00:00:00Z",
    createdBy: "system",
    updatedBy: "system",
  },
  {
    id: "3",
    groupId: "1",
    groupCode: "USER_LEVEL",
    groupName: "사용자 레벨",
    code: "USER",
    name: "사용자",
    description: "일반 사용 권한",
    value: "user",
    level: 1,
    sortOrder: 3,
    isActive: true,
    isSystem: true,
    attributes: { color: "#16a34a", icon: "shield" },
    createdAt: "2024-01-01T00:00:00Z",
    updatedAt: "2024-01-01T00:00:00Z",
    createdBy: "system",
    updatedBy: "system",
  },
  {
    id: "4",
    groupId: "1",
    groupCode: "USER_LEVEL",
    groupName: "사용자 레벨",
    code: "VIEWER",
    name: "조회자",
    description: "읽기 전용 권한",
    value: "viewer",
    level: 1,
    sortOrder: 4,
    isActive: true,
    isSystem: true,
    attributes: { color: "#6b7280", icon: "users" },
    createdAt: "2024-01-01T00:00:00Z",
    updatedAt: "2024-01-01T00:00:00Z",
    createdBy: "system",
    updatedBy: "system",
  },

  // 설비 유형
  {
    id: "5",
    groupId: "2",
    groupCode: "EQUIPMENT_TYPE",
    groupName: "설비 유형",
    code: "PRODUCTION",
    name: "생산설비",
    description: "제품 생산에 직접 사용되는 설비",
    level: 1,
    sortOrder: 1,
    isActive: true,
    isSystem: false,
    attributes: { color: "#059669" },
    createdAt: "2024-01-01T00:00:00Z",
    updatedAt: "2024-01-01T00:00:00Z",
    createdBy: "system",
    updatedBy: "system",
  },
  {
    id: "6",
    groupId: "2",
    groupCode: "EQUIPMENT_TYPE",
    groupName: "설비 유형",
    code: "PROD_MACHINE",
    name: "생산기계",
    description: "자동화 생산 기계",
    parentCode: "PRODUCTION",
    parentName: "생산설비",
    level: 2,
    sortOrder: 1,
    isActive: true,
    isSystem: false,
    attributes: { color: "#059669" },
    createdAt: "2024-01-01T00:00:00Z",
    updatedAt: "2024-01-01T00:00:00Z",
    createdBy: "system",
    updatedBy: "system",
  },
  {
    id: "7",
    groupId: "2",
    groupCode: "EQUIPMENT_TYPE",
    groupName: "설비 유형",
    code: "CONVEYOR",
    name: "컨베이어",
    description: "제품 이송용 컨베이어",
    parentCode: "PRODUCTION",
    parentName: "생산설비",
    level: 2,
    sortOrder: 2,
    isActive: true,
    isSystem: false,
    attributes: { color: "#059669" },
    createdAt: "2024-01-01T00:00:00Z",
    updatedAt: "2024-01-01T00:00:00Z",
    createdBy: "system",
    updatedBy: "system",
  },
  {
    id: "8",
    groupId: "2",
    groupCode: "EQUIPMENT_TYPE",
    groupName: "설비 유형",
    code: "UTILITY",
    name: "유틸리티",
    description: "전력, 공기, 물 등 공급 설비",
    level: 1,
    sortOrder: 2,
    isActive: true,
    isSystem: false,
    attributes: { color: "#dc2626" },
    createdAt: "2024-01-01T00:00:00Z",
    updatedAt: "2024-01-01T00:00:00Z",
    createdBy: "system",
    updatedBy: "system",
  },
  {
    id: "9",
    groupId: "2",
    groupCode: "EQUIPMENT_TYPE",
    groupName: "설비 유형",
    code: "COMPRESSOR",
    name: "압축기",
    description: "공기 압축 설비",
    parentCode: "UTILITY",
    parentName: "유틸리티",
    level: 2,
    sortOrder: 1,
    isActive: true,
    isSystem: false,
    attributes: { color: "#dc2626" },
    createdAt: "2024-01-01T00:00:00Z",
    updatedAt: "2024-01-01T00:00:00Z",
    createdBy: "system",
    updatedBy: "system",
  },

  // 보전 유형
  {
    id: "10",
    groupId: "3",
    groupCode: "MAINTENANCE_TYPE",
    groupName: "보전 유형",
    code: "PREVENTIVE",
    name: "예방정비",
    description: "계획된 예방 정비",
    level: 1,
    sortOrder: 1,
    isActive: true,
    isSystem: false,
    attributes: { color: "#2563eb" },
    createdAt: "2024-01-01T00:00:00Z",
    updatedAt: "2024-01-01T00:00:00Z",
    createdBy: "system",
    updatedBy: "system",
  },
  {
    id: "11",
    groupId: "3",
    groupCode: "MAINTENANCE_TYPE",
    groupName: "보전 유형",
    code: "CORRECTIVE",
    name: "사후정비",
    description: "고장 후 수리",
    level: 1,
    sortOrder: 2,
    isActive: true,
    isSystem: false,
    attributes: { color: "#dc2626" },
    createdAt: "2024-01-01T00:00:00Z",
    updatedAt: "2024-01-01T00:00:00Z",
    createdBy: "system",
    updatedBy: "system",
  },

  // 우선순위
  {
    id: "12",
    groupId: "5",
    groupCode: "PRIORITY",
    groupName: "우선순위",
    code: "CRITICAL",
    name: "긴급",
    description: "즉시 처리 필요",
    value: "1",
    level: 1,
    sortOrder: 1,
    isActive: true,
    isSystem: false,
    attributes: { color: "#dc2626", bgColor: "#fef2f2" },
    createdAt: "2024-01-01T00:00:00Z",
    updatedAt: "2024-01-01T00:00:00Z",
    createdBy: "system",
    updatedBy: "system",
  },
  {
    id: "13",
    groupId: "5",
    groupCode: "PRIORITY",
    groupName: "우선순위",
    code: "HIGH",
    name: "높음",
    description: "우선 처리",
    value: "2",
    level: 1,
    sortOrder: 2,
    isActive: true,
    isSystem: false,
    attributes: { color: "#ea580c", bgColor: "#fff7ed" },
    createdAt: "2024-01-01T00:00:00Z",
    updatedAt: "2024-01-01T00:00:00Z",
    createdBy: "system",
    updatedBy: "system",
  },
  {
    id: "14",
    groupId: "5",
    groupCode: "PRIORITY",
    groupName: "우선순위",
    code: "NORMAL",
    name: "보통",
    description: "일반 처리",
    value: "3",
    level: 1,
    sortOrder: 3,
    isActive: true,
    isSystem: false,
    attributes: { color: "#16a34a", bgColor: "#f0fdf4" },
    createdAt: "2024-01-01T00:00:00Z",
    updatedAt: "2024-01-01T00:00:00Z",
    createdBy: "system",
    updatedBy: "system",
  },
]
