import type { EquipmentType, EquipmentCategory, EquipmentCodeRule, EquipmentMaster } from "@fms/types"

// 설비 유형 목 데이터
export const mockEquipmentTypes: EquipmentType[] = [
  {
    id: "1",
    code: "COMPRESSOR",
    name: "압축기",
    description: "공기나 가스를 압축하는 설비",
    icon: "compressor",
    properties: [
      {
        id: "comp-1",
        code: "power",
        name: "동력",
        description: "압축기 동력 (kW)",
        dataType: "number",
        required: true,
        unit: "kW",
        min: 0,
        max: 1000,
        order: 1,
        isActive: true,
      },
      {
        id: "comp-2",
        code: "pressure",
        name: "압력",
        description: "최대 압력 (bar)",
        dataType: "number",
        required: true,
        unit: "bar",
        min: 0,
        max: 100,
        order: 2,
        isActive: true,
      },
      {
        id: "comp-3",
        code: "capacity",
        name: "용량",
        description: "공기 용량 (L/min)",
        dataType: "number",
        required: true,
        unit: "L/min",
        min: 0,
        max: 10000,
        order: 3,
        isActive: true,
      },
      {
        id: "comp-4",
        code: "type",
        name: "압축기 종류",
        description: "압축기 종류",
        dataType: "select",
        required: true,
        options: [
          { label: "왕복동식", value: "reciprocating" },
          { label: "스크류식", value: "screw" },
          { label: "원심식", value: "centrifugal" },
          { label: "스크롤식", value: "scroll" },
        ],
        order: 4,
        isActive: true,
      },
    ],
    isActive: true,
    createdAt: "2023-01-01T00:00:00Z",
    updatedAt: "2023-01-01T00:00:00Z",
    createdBy: "admin",
    updatedBy: "admin",
  },
  {
    id: "2",
    code: "CONVEYOR",
    name: "컨베이어",
    description: "물건을 운반하는 설비",
    icon: "conveyor",
    properties: [
      {
        id: "conv-1",
        code: "length",
        name: "길이",
        description: "컨베이어 길이 (m)",
        dataType: "number",
        required: true,
        unit: "m",
        min: 0,
        max: 1000,
        order: 1,
        isActive: true,
      },
      {
        id: "conv-2",
        code: "width",
        name: "폭",
        description: "컨베이어 폭 (m)",
        dataType: "number",
        required: true,
        unit: "m",
        min: 0,
        max: 10,
        order: 2,
        isActive: true,
      },
      {
        id: "conv-3",
        code: "speed",
        name: "속도",
        description: "컨베이어 속도 (m/s)",
        dataType: "number",
        required: true,
        unit: "m/s",
        min: 0,
        max: 10,
        order: 3,
        isActive: true,
      },
      {
        id: "conv-4",
        code: "capacity",
        name: "적재용량",
        description: "최대 적재용량 (kg)",
        dataType: "number",
        required: true,
        unit: "kg",
        min: 0,
        max: 10000,
        order: 4,
        isActive: true,
      },
      {
        id: "conv-5",
        code: "type",
        name: "컨베이어 종류",
        description: "컨베이어 종류",
        dataType: "select",
        required: true,
        options: [
          { label: "벨트형", value: "belt" },
          { label: "롤러형", value: "roller" },
          { label: "체인형", value: "chain" },
          { label: "스크류형", value: "screw" },
        ],
        order: 5,
        isActive: true,
      },
    ],
    isActive: true,
    createdAt: "2023-01-01T00:00:00Z",
    updatedAt: "2023-01-01T00:00:00Z",
    createdBy: "admin",
    updatedBy: "admin",
  },
  {
    id: "3",
    code: "PUMP",
    name: "펌프",
    description: "액체를 이동시키는 설비",
    icon: "pump",
    properties: [
      {
        id: "pump-1",
        code: "flow",
        name: "유량",
        description: "펌프 유량 (L/min)",
        dataType: "number",
        required: true,
        unit: "L/min",
        min: 0,
        max: 10000,
        order: 1,
        isActive: true,
      },
      {
        id: "pump-2",
        code: "head",
        name: "양정",
        description: "펌프 양정 (m)",
        dataType: "number",
        required: true,
        unit: "m",
        min: 0,
        max: 1000,
        order: 2,
        isActive: true,
      },
      {
        id: "pump-3",
        code: "power",
        name: "동력",
        description: "펌프 동력 (kW)",
        dataType: "number",
        required: true,
        unit: "kW",
        min: 0,
        max: 1000,
        order: 3,
        isActive: true,
      },
      {
        id: "pump-4",
        code: "type",
        name: "펌프 종류",
        description: "펌프 종류",
        dataType: "select",
        required: true,
        options: [
          { label: "원심펌프", value: "centrifugal" },
          { label: "왕복펌프", value: "reciprocating" },
          { label: "회전펌프", value: "rotary" },
          { label: "다이어프램펌프", value: "diaphragm" },
        ],
        order: 4,
        isActive: true,
      },
    ],
    isActive: true,
    createdAt: "2023-01-01T00:00:00Z",
    updatedAt: "2023-01-01T00:00:00Z",
    createdBy: "admin",
    updatedBy: "admin",
  },
  {
    id: "4",
    code: "ROBOT",
    name: "로봇",
    description: "자동화된 작업을 수행하는 설비",
    icon: "robot",
    properties: [
      {
        id: "robot-1",
        code: "reach",
        name: "작업반경",
        description: "로봇 작업반경 (m)",
        dataType: "number",
        required: true,
        unit: "m",
        min: 0,
        max: 10,
        order: 1,
        isActive: true,
      },
      {
        id: "robot-2",
        code: "payload",
        name: "적재용량",
        description: "최대 적재용량 (kg)",
        dataType: "number",
        required: true,
        unit: "kg",
        min: 0,
        max: 1000,
        order: 2,
        isActive: true,
      },
      {
        id: "robot-3",
        code: "repeatability",
        name: "반복정밀도",
        description: "반복정밀도 (mm)",
        dataType: "string",
        required: true,
        order: 3,
        isActive: true,
      },
      {
        id: "robot-4",
        code: "axes",
        name: "축 수",
        description: "로봇 축 수",
        dataType: "number",
        required: true,
        min: 1,
        max: 10,
        order: 4,
        isActive: true,
      },
      {
        id: "robot-5",
        code: "type",
        name: "로봇 종류",
        description: "로봇 종류",
        dataType: "select",
        required: true,
        options: [
          { label: "다관절로봇", value: "articulated" },
          { label: "직교로봇", value: "cartesian" },
          { label: "스카라로봇", value: "scara" },
          { label: "델타로봇", value: "delta" },
        ],
        order: 5,
        isActive: true,
      },
    ],
    isActive: true,
    createdAt: "2023-01-01T00:00:00Z",
    updatedAt: "2023-01-01T00:00:00Z",
    createdBy: "admin",
    updatedBy: "admin",
  },
  {
    id: "5",
    code: "CRANE",
    name: "크레인",
    description: "중량물을 들어올리는 설비",
    icon: "crane",
    properties: [
      {
        id: "crane-1",
        code: "capacity",
        name: "용량",
        description: "최대 용량 (ton)",
        dataType: "number",
        required: true,
        unit: "ton",
        min: 0,
        max: 1000,
        order: 1,
        isActive: true,
      },
      {
        id: "crane-2",
        code: "span",
        name: "스팬",
        description: "크레인 스팬 (m)",
        dataType: "number",
        required: true,
        unit: "m",
        min: 0,
        max: 100,
        order: 2,
        isActive: true,
      },
      {
        id: "crane-3",
        code: "height",
        name: "높이",
        description: "크레인 높이 (m)",
        dataType: "number",
        required: true,
        unit: "m",
        min: 0,
        max: 100,
        order: 3,
        isActive: true,
      },
      {
        id: "crane-4",
        code: "type",
        name: "크레인 종류",
        description: "크레인 종류",
        dataType: "select",
        required: true,
        options: [
          { label: "천장크레인", value: "overhead" },
          { label: "갠트리크레인", value: "gantry" },
          { label: "지브크레인", value: "jib" },
          { label: "타워크레인", value: "tower" },
        ],
        order: 4,
        isActive: true,
      },
    ],
    isActive: true,
    createdAt: "2023-01-01T00:00:00Z",
    updatedAt: "2023-01-01T00:00:00Z",
    createdBy: "admin",
    updatedBy: "admin",
  },
]

// 설비 분류 목 데이터
export const mockEquipmentCategories: EquipmentCategory[] = [
  {
    id: "1",
    code: "PROD",
    name: "생산설비",
    level: 1,
    path: "PROD",
    description: "제품 생산에 직접 관여하는 설비",
    isActive: true,
    children: [
      {
        id: "1-1",
        code: "PROD-ASSY",
        name: "조립설비",
        parentId: "1",
        level: 2,
        path: "PROD/PROD-ASSY",
        description: "부품을 조립하는 설비",
        isActive: true,
      },
      {
        id: "1-2",
        code: "PROD-MOLD",
        name: "성형설비",
        parentId: "1",
        level: 2,
        path: "PROD/PROD-MOLD",
        description: "제품을 성형하는 설비",
        isActive: true,
      },
      {
        id: "1-3",
        code: "PROD-WELD",
        name: "용접설비",
        parentId: "1",
        level: 2,
        path: "PROD/PROD-WELD",
        description: "부품을 용접하는 설비",
        isActive: true,
      },
    ],
  },
  {
    id: "2",
    code: "INSP",
    name: "검사설비",
    level: 1,
    path: "INSP",
    description: "제품 품질을 검사하는 설비",
    isActive: true,
    children: [
      {
        id: "2-1",
        code: "INSP-VISION",
        name: "비전검사설비",
        parentId: "2",
        level: 2,
        path: "INSP/INSP-VISION",
        description: "카메라로 제품을 검사하는 설비",
        isActive: true,
      },
      {
        id: "2-2",
        code: "INSP-DIM",
        name: "치수검사설비",
        parentId: "2",
        level: 2,
        path: "INSP/INSP-DIM",
        description: "제품 치수를 검사하는 설비",
        isActive: true,
      },
    ],
  },
  {
    id: "3",
    code: "UTIL",
    name: "유틸리티설비",
    level: 1,
    path: "UTIL",
    description: "공장 운영에 필요한 유틸리티 설비",
    isActive: true,
    children: [
      {
        id: "3-1",
        code: "UTIL-AIR",
        name: "공기공급설비",
        parentId: "3",
        level: 2,
        path: "UTIL/UTIL-AIR",
        description: "압축공기를 공급하는 설비",
        isActive: true,
      },
      {
        id: "3-2",
        code: "UTIL-WATER",
        name: "용수공급설비",
        parentId: "3",
        level: 2,
        path: "UTIL/UTIL-WATER",
        description: "용수를 공급하는 설비",
        isActive: true,
      },
      {
        id: "3-3",
        code: "UTIL-POWER",
        name: "전력공급설비",
        parentId: "3",
        level: 2,
        path: "UTIL/UTIL-POWER",
        description: "전력을 공급하는 설비",
        isActive: true,
      },
    ],
  },
  {
    id: "4",
    code: "TRAN",
    name: "운반설비",
    level: 1,
    path: "TRAN",
    description: "물건을 운반하는 설비",
    isActive: true,
    children: [
      {
        id: "4-1",
        code: "TRAN-CONV",
        name: "컨베이어",
        parentId: "4",
        level: 2,
        path: "TRAN/TRAN-CONV",
        description: "컨베이어 벨트 설비",
        isActive: true,
      },
      {
        id: "4-2",
        code: "TRAN-LIFT",
        name: "리프트",
        parentId: "4",
        level: 2,
        path: "TRAN/TRAN-LIFT",
        description: "수직 운반 설비",
        isActive: true,
      },
    ],
  },
]

// 설비 코드 규칙 목 데이터
export const mockEquipmentCodeRules: EquipmentCodeRule[] = [
  {
    id: "1",
    name: "표준 설비 코드",
    prefix: "EQ",
    separator: "-",
    segments: [
      {
        id: "1-1",
        type: "fixed",
        value: "EQ",
        length: 2,
        description: "설비 접두어",
      },
      {
        id: "1-2",
        type: "category",
        length: 4,
        padChar: "",
        description: "설비 분류 코드",
      },
      {
        id: "1-3",
        type: "sequence",
        length: 3,
        padChar: "0",
        description: "일련번호",
      },
    ],
    example: "EQ-COMP-001",
    isActive: true,
    appliedTo: ["1", "2", "3", "4", "5"], // 모든 설비 유형에 적용
    description: "모든 설비에 적용되는 표준 코드 체계",
    createdAt: "2023-01-01T00:00:00Z",
    updatedAt: "2023-01-01T00:00:00Z",
  },
  {
    id: "2",
    name: "생산설비 코드",
    prefix: "PROD",
    separator: "-",
    segments: [
      {
        id: "2-1",
        type: "fixed",
        value: "PROD",
        length: 4,
        description: "생산설비 접두어",
      },
      {
        id: "2-2",
        type: "location",
        length: 2,
        padChar: "",
        description: "설치 위치 코드",
      },
      {
        id: "2-3",
        type: "sequence",
        length: 3,
        padChar: "0",
        description: "일련번호",
      },
    ],
    example: "PROD-A1-001",
    isActive: true,
    appliedTo: ["1", "4"], // 압축기, 로봇에만 적용
    description: "생산 라인 설비에 적용되는 코드 체계",
    createdAt: "2023-01-01T00:00:00Z",
    updatedAt: "2023-01-01T00:00:00Z",
  },
  {
    id: "3",
    name: "유틸리티 설비 코드",
    prefix: "UTIL",
    separator: "_",
    segments: [
      {
        id: "3-1",
        type: "fixed",
        value: "UTIL",
        length: 4,
        description: "유틸리티 접두어",
      },
      {
        id: "3-2",
        type: "custom",
        value: "TYPE",
        length: 3,
        padChar: "",
        description: "설비 유형 약어",
      },
      {
        id: "3-3",
        type: "year",
        length: 2,
        padChar: "",
        description: "설치 연도",
      },
      {
        id: "3-4",
        type: "sequence",
        length: 2,
        padChar: "0",
        description: "일련번호",
      },
    ],
    example: "UTIL_AIR_23_01",
    isActive: true,
    appliedTo: ["1", "3"], // 압축기, 펌프에만 적용
    description: "유틸리티 설비에 적용되는 코드 체계",
    createdAt: "2023-01-01T00:00:00Z",
    updatedAt: "2023-01-01T00:00:00Z",
  },
]

// --- NEW MOCK DATA FOR EQUIPMENT MASTER ---
export const mockEquipmentMasterData: EquipmentMaster[] = [
  {
    id: "eqm-001",
    equipmentId: "EQ-COMP-001", // Generated using standard rule
    equipmentName: "공기 압축기 #1",
    equipmentTypeId: "1", // Compressor
    equipmentCategoryId: "3-1", // UTIL-AIR
    model: "GA 37 VSD+",
    manufacturer: "Atlas Copco",
    serialNumber: "SN-COMP-001",
    installationDate: new Date("2023-01-15"),
    status: "active",
    location: "유틸리티실 A",
    department: "생산1팀",
    description: "주요 공기 공급원",
    purchaseDate: new Date("2022-12-01"),
    purchasePrice: 25000000,
    warrantyExpiryDate: new Date("2025-01-15"),
    lastMaintenanceDate: new Date("2024-05-01"),
    nextMaintenanceDate: new Date("2024-11-01"),
    customFields: { power: 37, pressure: 7.5, capacity: 6000, type: "screw" },
    qrCodeValue: "EQ-COMP-001",
    createdAt: new Date(),
    updatedAt: new Date(),
    createdBy: "admin",
    updatedBy: "admin",
  },
  {
    id: "eqm-002",
    equipmentId: "PROD-A1-001", // Generated using production rule
    equipmentName: "조립 로봇 #1",
    equipmentTypeId: "4", // Robot
    equipmentCategoryId: "1-1", // PROD-ASSY
    model: "IRB 1200",
    manufacturer: "ABB",
    serialNumber: "SN-ROBOT-001",
    installationDate: new Date("2023-03-20"),
    status: "active",
    location: "A라인 셀 3",
    department: "생산2팀",
    description: "소형 부품 조립용 6축 로봇",
    purchaseDate: new Date("2023-02-10"),
    purchasePrice: 45000000,
    warrantyExpiryDate: new Date("2025-03-20"),
    lastMaintenanceDate: new Date("2024-06-10"),
    nextMaintenanceDate: new Date("2024-12-10"),
    customFields: { reach: 0.9, payload: 5, repeatability: "±0.02mm", axes: 6, type: "articulated" },
    qrCodeValue: "PROD-A1-001",
    createdAt: new Date(),
    updatedAt: new Date(),
    createdBy: "admin",
    updatedBy: "admin",
  },
  {
    id: "eqm-003",
    equipmentId: "EQ-CONV-001",
    equipmentName: "제품 이송 컨베이어",
    equipmentTypeId: "2", // Conveyor
    equipmentCategoryId: "4-1", // TRAN-CONV
    model: "BeltMaster 500",
    manufacturer: "Interroll",
    serialNumber: "SN-CONV-001",
    installationDate: new Date("2022-11-05"),
    status: "maintenance",
    location: "포장 라인",
    department: "물류팀",
    description: "완제품 포장대로 이송",
    purchaseDate: new Date("2022-10-01"),
    purchasePrice: 12000000,
    warrantyExpiryDate: new Date("2024-11-05"),
    lastMaintenanceDate: new Date("2024-05-20"),
    nextMaintenanceDate: new Date("2024-07-01"),
    customFields: { length: 10, width: 0.8, speed: 0.5, capacity: 500, type: "belt" },
    qrCodeValue: "EQ-CONV-001",
    createdAt: new Date(),
    updatedAt: new Date(),
    createdBy: "admin",
    updatedBy: "admin",
  },
  {
    id: "eqm-004",
    equipmentId: "UTIL_PMP_23_01", // Generated using utility rule
    equipmentName: "냉각수 펌프 #1",
    equipmentTypeId: "3", // Pump
    equipmentCategoryId: "3-2", // UTIL-WATER (assuming cooling water)
    model: "CRNE 5-5",
    manufacturer: "Grundfos",
    serialNumber: "SN-PUMP-001",
    installationDate: new Date("2023-06-01"),
    status: "active",
    location: "유틸리티실 B",
    department: "시설관리팀",
    description: "금형 냉각수 순환 펌프",
    purchaseDate: new Date("2023-05-15"),
    purchasePrice: 8000000,
    warrantyExpiryDate: new Date("2025-06-01"),
    lastMaintenanceDate: new Date("2024-04-15"),
    nextMaintenanceDate: new Date("2024-10-15"),
    customFields: { flow: 300, head: 50, power: 5.5, type: "centrifugal" },
    qrCodeValue: "UTIL_PMP_23_01",
    createdAt: new Date(),
    updatedAt: new Date(),
    createdBy: "admin",
    updatedBy: "admin",
  },
  {
    id: "eqm-005",
    equipmentId: "EQ-CRAN-001",
    equipmentName: "천장 크레인 5톤",
    equipmentTypeId: "5", // Crane
    equipmentCategoryId: "4", // TRAN (assuming general transport, could be more specific)
    model: "Overhead 5T",
    manufacturer: "Konecranes",
    serialNumber: "SN-CRANE-001",
    installationDate: new Date("2021-08-10"),
    status: "inactive",
    location: "원자재 창고",
    department: "물류팀",
    description: "원자재 입출고용 크레인",
    purchaseDate: new Date("2021-07-01"),
    purchasePrice: 75000000,
    warrantyExpiryDate: new Date("2023-08-10"), // Expired
    lastMaintenanceDate: new Date("2024-02-01"),
    nextMaintenanceDate: new Date("2024-08-01"),
    customFields: { capacity: 5, span: 15, height: 8, type: "overhead" },
    qrCodeValue: "EQ-CRAN-001",
    createdAt: new Date(),
    updatedAt: new Date(),
    createdBy: "admin",
    updatedBy: "admin",
  },
]
