import type { EquipmentDocument } from "@fms/types"

export const mockEquipmentDocuments: EquipmentDocument[] = [
  {
    id: "doc-001",
    equipmentId: "eq-001",
    equipmentCode: "EQ-001",
    equipmentName: "CNC 밀링머신 #1",
    title: "CNC 밀링머신 운영 매뉴얼",
    description: "CNC 밀링머신의 기본 운영 및 조작 방법에 대한 매뉴얼",
    category: "manual",
    type: "pdf",
    filename: "cnc_milling_manual_v2.1.pdf",
    originalName: "CNC밀링머신_운영매뉴얼_v2.1.pdf",
    fileSize: 2048576,
    mimeType: "application/pdf",
    url: "/documents/cnc_milling_manual_v2.1.pdf",
    version: "2.1",
    status: "approved",
    tags: ["운영", "조작", "안전"],
    uploadedAt: "2024-01-15T09:00:00Z",
    uploadedBy: "김기술",
    updatedAt: "2024-01-15T09:00:00Z",
    updatedBy: "김기술",
    approvedAt: "2024-01-16T14:30:00Z",
    approvedBy: "박관리",
    isActive: true,
  },
  {
    id: "doc-002",
    equipmentId: "eq-001",
    equipmentCode: "EQ-001",
    equipmentName: "CNC 밀링머신 #1",
    title: "전기 회로도",
    description: "CNC 밀링머신의 전기 회로도 및 배선도",
    category: "drawing",
    type: "dwg",
    filename: "cnc_electrical_drawing_v1.0.dwg",
    originalName: "CNC_전기회로도_v1.0.dwg",
    fileSize: 1024000,
    mimeType: "application/acad",
    url: "/documents/cnc_electrical_drawing_v1.0.dwg",
    version: "1.0",
    status: "approved",
    tags: ["전기", "회로도", "배선"],
    uploadedAt: "2024-01-10T11:30:00Z",
    uploadedBy: "이전기",
    updatedAt: "2024-01-10T11:30:00Z",
    updatedBy: "이전기",
    approvedAt: "2024-01-11T16:00:00Z",
    approvedBy: "박관리",
    isActive: true,
  },
  {
    id: "doc-003",
    equipmentId: "eq-002",
    equipmentCode: "EQ-002",
    equipmentName: "자동화 라인 #1",
    title: "CE 인증서",
    description: "자동화 라인의 CE 마크 적합성 인증서",
    category: "certificate",
    type: "pdf",
    filename: "automation_line_ce_certificate.pdf",
    originalName: "자동화라인_CE인증서.pdf",
    fileSize: 512000,
    mimeType: "application/pdf",
    url: "/documents/automation_line_ce_certificate.pdf",
    version: "1.0",
    status: "approved",
    tags: ["인증", "CE", "안전"],
    uploadedAt: "2024-01-05T14:20:00Z",
    uploadedBy: "최품질",
    updatedAt: "2024-01-05T14:20:00Z",
    updatedBy: "최품질",
    approvedAt: "2024-01-06T10:15:00Z",
    approvedBy: "박관리",
    expiryDate: "2027-01-05",
    isActive: true,
  },
  {
    id: "doc-004",
    equipmentId: "eq-001",
    equipmentCode: "EQ-001",
    equipmentName: "CNC 밀링머신 #1",
    title: "정기 점검 체크리스트",
    description: "월간 정기 점검을 위한 체크리스트",
    category: "maintenance",
    type: "xlsx",
    filename: "cnc_monthly_checklist_v1.2.xlsx",
    originalName: "CNC_월간점검체크리스트_v1.2.xlsx",
    fileSize: 256000,
    mimeType: "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
    url: "/documents/cnc_monthly_checklist_v1.2.xlsx",
    version: "1.2",
    status: "approved",
    tags: ["점검", "체크리스트", "정기"],
    uploadedAt: "2024-01-20T08:45:00Z",
    uploadedBy: "정정비",
    updatedAt: "2024-01-20T08:45:00Z",
    updatedBy: "정정비",
    approvedAt: "2024-01-21T13:20:00Z",
    approvedBy: "박관리",
    isActive: true,
  },
  {
    id: "doc-005",
    equipmentId: "eq-003",
    equipmentCode: "EQ-003",
    equipmentName: "컨베이어 시스템",
    title: "안전 운영 수칙",
    description: "컨베이어 시스템 안전 운영을 위한 수칙 및 주의사항",
    category: "safety",
    type: "pdf",
    filename: "conveyor_safety_rules_v1.0.pdf",
    originalName: "컨베이어_안전운영수칙_v1.0.pdf",
    fileSize: 768000,
    mimeType: "application/pdf",
    url: "/documents/conveyor_safety_rules_v1.0.pdf",
    version: "1.0",
    status: "review",
    tags: ["안전", "운영수칙", "주의사항"],
    uploadedAt: "2024-01-25T16:10:00Z",
    uploadedBy: "안안전",
    updatedAt: "2024-01-25T16:10:00Z",
    updatedBy: "안안전",
    isActive: true,
  },
]

export const documentCategories = [
  { value: "manual", label: "매뉴얼" },
  { value: "drawing", label: "도면" },
  { value: "certificate", label: "인증서" },
  { value: "specification", label: "사양서" },
  { value: "maintenance", label: "정비지침서" },
  { value: "safety", label: "안전수칙" },
  { value: "other", label: "기타" },
]

export const documentStatuses = [
  { value: "draft", label: "초안", color: "gray" },
  { value: "review_requested", label: "검토요청", color: "blue" },
  { value: "review", label: "검토중", color: "yellow" },
  { value: "approved", label: "승인됨", color: "green" },
  { value: "rejected", label: "반려됨", color: "red" },
  { value: "expired", label: "만료됨", color: "orange" },
  { value: "archived", label: "보관됨", color: "purple" },
]
