import type { EquipmentHealthDetail, HealthTrendData } from "@fms/types"

export const mockEquipmentHealthDetails: EquipmentHealthDetail[] = [
  {
    equipmentId: "EQ001",
    equipmentName: "CNC 가공기 #1",
    equipmentType: "가공설비",
    location: "1공장 A라인",
    healthScore: 92,
    healthGrade: "A",
    riskLevel: "low",
    trend: "stable",
    factors: {
      reliability: 95,
      availability: 88,
      maintainability: 92,
      performance: 94,
    },
    metrics: {
      mtbf: 720,
      mttr: 4.2,
      uptime: 88.5,
      efficiency: 94.2,
      vibration: 2.1,
      temperature: 45.2,
      pressure: 6.8,
    },
    history: [
      { date: "2024-01", healthScore: 89 },
      { date: "2024-02", healthScore: 91, event: "정기점검" },
      { date: "2024-03", healthScore: 92 },
      { date: "2024-04", healthScore: 92 },
      { date: "2024-05", healthScore: 92 },
    ],
    issues: [],
    recommendations: [
      {
        priority: "medium",
        action: "냉각수 교체 주기 단축",
        expectedImprovement: 2,
        estimatedCost: 50000,
      },
    ],
    lastInspection: "2024-05-15",
    nextInspection: "2024-06-15",
    lastMaintenance: "2024-04-20",
    nextMaintenance: "2024-07-20",
  },
  {
    equipmentId: "EQ002",
    equipmentName: "프레스 #2",
    equipmentType: "성형설비",
    location: "2공장 B라인",
    healthScore: 76,
    healthGrade: "C",
    riskLevel: "medium",
    trend: "declining",
    factors: {
      reliability: 78,
      availability: 82,
      maintainability: 74,
      performance: 70,
    },
    metrics: {
      mtbf: 480,
      mttr: 8.5,
      uptime: 82.1,
      efficiency: 70.8,
      vibration: 4.2,
      temperature: 52.8,
      pressure: 8.2,
    },
    history: [
      { date: "2024-01", healthScore: 82 },
      { date: "2024-02", healthScore: 80 },
      { date: "2024-03", healthScore: 78, event: "유압 문제" },
      { date: "2024-04", healthScore: 76 },
      { date: "2024-05", healthScore: 76 },
    ],
    issues: ["유압 시스템 압력 불안정", "진동 수준 증가", "효율성 저하"],
    recommendations: [
      {
        priority: "high",
        action: "유압 시스템 오버홀",
        expectedImprovement: 8,
        estimatedCost: 2000000,
      },
      {
        priority: "medium",
        action: "진동 센서 교체",
        expectedImprovement: 3,
        estimatedCost: 300000,
      },
    ],
    lastInspection: "2024-05-10",
    nextInspection: "2024-06-10",
    lastMaintenance: "2024-03-15",
    nextMaintenance: "2024-06-15",
  },
  {
    equipmentId: "EQ003",
    equipmentName: "컨베이어 시스템 #1",
    equipmentType: "운반설비",
    location: "1공장 메인라인",
    healthScore: 65,
    healthGrade: "D",
    riskLevel: "high",
    trend: "declining",
    factors: {
      reliability: 68,
      availability: 75,
      maintainability: 62,
      performance: 55,
    },
    metrics: {
      mtbf: 320,
      mttr: 12.3,
      uptime: 75.2,
      efficiency: 55.4,
      vibration: 6.1,
      temperature: 48.5,
      pressure: 5.2,
    },
    history: [
      { date: "2024-01", healthScore: 75 },
      { date: "2024-02", healthScore: 72, event: "모터 교체" },
      { date: "2024-03", healthScore: 68 },
      { date: "2024-04", healthScore: 66, event: "벨트 교체" },
      { date: "2024-05", healthScore: 65 },
    ],
    issues: ["모터 과열 빈발", "벨트 마모 심각", "베어링 소음 증가", "속도 제어 불안정"],
    recommendations: [
      {
        priority: "high",
        action: "모터 시스템 전면 교체",
        expectedImprovement: 15,
        estimatedCost: 5000000,
      },
      {
        priority: "high",
        action: "구동 벨트 전체 교체",
        expectedImprovement: 8,
        estimatedCost: 800000,
      },
      {
        priority: "medium",
        action: "베어링 교체",
        expectedImprovement: 5,
        estimatedCost: 400000,
      },
    ],
    lastInspection: "2024-05-08",
    nextInspection: "2024-05-22",
    lastMaintenance: "2024-04-25",
    nextMaintenance: "2024-06-01",
  },
]

export const mockHealthTrendData: HealthTrendData[] = [
  { date: "2024-01", overallHealth: 82, reliability: 84, availability: 85, maintainability: 79, performance: 80 },
  { date: "2024-02", overallHealth: 81, reliability: 83, availability: 84, maintainability: 78, performance: 79 },
  { date: "2024-03", overallHealth: 79, reliability: 81, availability: 82, maintainability: 76, performance: 77 },
  { date: "2024-04", overallHealth: 78, reliability: 80, availability: 81, maintainability: 76, performance: 75 },
  { date: "2024-05", overallHealth: 78, reliability: 80, availability: 81, maintainability: 76, performance: 74 },
]
