import { type Failure, FailureType, FailurePriority, FailureStatus } from "@fms/types"

export const mockFailures: Failure[] = [
  {
    id: "failure-1",
    equipmentId: "equip-1",
    equipmentName: "컨베이어 #1",
    title: "컨베이어 벨트 이상",
    description: "컨베이어 벨트가 미끄러지며 정상 작동하지 않음",
    type: FailureType.MECHANICAL,
    priority: FailurePriority.HIGH,
    status: FailureStatus.REPORTED,
    reportedAt: "2025-05-15T08:30:00Z",
    reporterName: "김작업자",
    reporterContact: "010-1234-5678",
    symptom: "벨트가 미끄러지며 제품이 정상적으로 이동하지 않음",
    possibleCauses: "벨트 장력 부족, 구동 모터 출력 저하",
    recommendedActions: "벨트 장력 조정, 모터 점검",
    preventionMethods: "정기적인 벨트 장력 점검",
    attachments: [],
    estimatedCost: 200000,
    actualCost: 0,
    downtimeHours: 0,
    createdAt: "2025-05-15T08:30:00Z",
    updatedAt: "2025-05-15T08:30:00Z",
  },
  {
    id: "failure-2",
    equipmentId: "equip-2",
    equipmentName: "프레스 #2",
    title: "유압 누유",
    description: "유압 실린더에서 오일 누유 발생",
    type: FailureType.HYDRAULIC,
    priority: FailurePriority.EMERGENCY,
    status: FailureStatus.IN_REPAIR,
    reportedAt: "2025-05-14T10:15:00Z",
    reporterName: "박기술",
    reporterContact: "010-2345-6789",
    symptom: "유압 실린더 하단에서 오일 누유, 압력 저하",
    possibleCauses: "실린더 씰 손상, 연결부 풀림",
    recommendedActions: "실린더 씰 교체, 연결부 조임",
    preventionMethods: "정기적인 씰 상태 점검",
    attachments: [],
    estimatedCost: 500000,
    actualCost: 450000,
    downtimeHours: 4,
    createdAt: "2025-05-14T10:15:00Z",
    updatedAt: "2025-05-14T14:30:00Z",
  },
  {
    id: "failure-3",
    equipmentId: "equip-3",
    equipmentName: "로봇 #1",
    title: "제어 오류",
    description: "로봇 팔 위치 제어 오류 발생",
    type: FailureType.CONTROL,
    priority: FailurePriority.MEDIUM,
    status: FailureStatus.DIAGNOSED,
    reportedAt: "2025-05-13T15:45:00Z",
    reporterName: "이공정",
    reporterContact: "010-3456-7890",
    symptom: "로봇 팔이 지정된 위치에 정확히 도달하지 못함",
    possibleCauses: "엔코더 오류, 제어 파라미터 이상",
    recommendedActions: "엔코더 교정, 제어 파라미터 재설정",
    preventionMethods: "정기적인 위치 정확도 점검",
    attachments: [],
    estimatedCost: 300000,
    actualCost: 0,
    downtimeHours: 2,
    createdAt: "2025-05-13T15:45:00Z",
    updatedAt: "2025-05-13T17:30:00Z",
  },
  {
    id: "failure-4",
    equipmentId: "equip-4",
    equipmentName: "에어 컴프레서 #1",
    title: "과열 발생",
    description: "컴프레서 과열로 자동 정지",
    type: FailureType.PNEUMATIC,
    priority: FailurePriority.HIGH,
    status: FailureStatus.COMPLETED,
    reportedAt: "2025-05-12T09:20:00Z",
    reporterName: "최설비",
    reporterContact: "010-4567-8901",
    symptom: "컴프레서 온도 상승 후 자동 정지, 경고등 점등",
    possibleCauses: "냉각 팬 고장, 필터 막힘, 과부하 운전",
    recommendedActions: "냉각 팬 교체, 필터 청소, 운전 조건 조정",
    preventionMethods: "정기적인 필터 청소 및 냉각 시스템 점검",
    attachments: [],
    estimatedCost: 400000,
    actualCost: 380000,
    downtimeHours: 6,
    completedAt: "2025-05-12T15:30:00Z",
    createdAt: "2025-05-12T09:20:00Z",
    updatedAt: "2025-05-12T15:30:00Z",
  },
  {
    id: "failure-5",
    equipmentId: "equip-5",
    equipmentName: "전기 패널 #2",
    title: "회로 차단기 작동",
    description: "메인 회로 차단기 트립 발생",
    type: FailureType.ELECTRICAL,
    priority: FailurePriority.EMERGENCY,
    status: FailureStatus.COMPLETED,
    reportedAt: "2025-05-11T14:10:00Z",
    reporterName: "정전기",
    reporterContact: "010-5678-9012",
    symptom: "갑작스러운 전원 차단, 회로 차단기 트립 상태 확인",
    possibleCauses: "과부하, 단락, 접지 오류",
    recommendedActions: "회로 점검, 부하 측정, 절연 상태 확인",
    preventionMethods: "정기적인 전기 부하 측정 및 절연 상태 점검",
    attachments: [],
    estimatedCost: 150000,
    actualCost: 120000,
    downtimeHours: 3,
    completedAt: "2025-05-11T17:20:00Z",
    createdAt: "2025-05-11T14:10:00Z",
    updatedAt: "2025-05-11T17:20:00Z",
  },
]
