import type { InspectionSchedule } from "@fms/types"

// 현재 날짜 기준으로 날짜 생성 함수
const getDate = (dayOffset: number) => {
  const date = new Date()
  date.setDate(date.getDate() + dayOffset)
  return date.toISOString().split("T")[0]
}

export const mockInspectionSchedules: InspectionSchedule[] = [
  {
    id: "1",
    standardId: "1",
    standard: {
      id: "1",
      name: "압축기 일일점검",
      version: "1.2",
      type: "daily",
    },
    equipmentId: "1",
    equipment: {
      id: "1",
      code: "COMP-A1-001",
      name: "공기압축기 #1",
      location: "A동 1층",
      department: "생산1팀",
    },
    scheduledDate: getDate(0),
    scheduledTime: "09:00",
    estimatedDuration: 30,
    assignedToId: "1",
    assignedTo: {
      id: "1",
      name: "김기술",
      department: "설비보전팀",
      position: "주임",
    },
    status: "scheduled",
    priority: "medium",
    createdAt: "2024-05-25T10:00:00Z",
    updatedAt: "2024-05-25T10:00:00Z",
    createdBy: "admin",
    updatedBy: "admin",
    recurrencePattern: "daily",
  },
  {
    id: "2",
    standardId: "2",
    standard: {
      id: "2",
      name: "배기팬 월간점검",
      version: "1.0",
      type: "monthly",
    },
    equipmentId: "2",
    equipment: {
      id: "2",
      code: "FAN-B2-002",
      name: "배기팬 #2",
      location: "B동 2층",
      department: "생산2팀",
    },
    scheduledDate: getDate(7),
    scheduledTime: "14:00",
    estimatedDuration: 60,
    assignedToId: "2",
    assignedTo: {
      id: "2",
      name: "박엔지니어",
      department: "설비보전팀",
      position: "대리",
    },
    status: "scheduled",
    priority: "low",
    createdAt: "2024-05-20T11:30:00Z",
    updatedAt: "2024-05-20T11:30:00Z",
    createdBy: "admin",
    updatedBy: "admin",
    recurrencePattern: "monthly",
  },
  {
    id: "3",
    standardId: "3",
    standard: {
      id: "3",
      name: "냉각수 펌프 주간점검",
      version: "1.1",
      type: "weekly",
    },
    equipmentId: "3",
    equipment: {
      id: "3",
      code: "PUMP-C3-003",
      name: "냉각수 펌프 #3",
      location: "C동 3층",
      department: "설비보전팀",
    },
    scheduledDate: getDate(2),
    scheduledTime: "10:30",
    estimatedDuration: 45,
    assignedToId: "3",
    assignedTo: {
      id: "3",
      name: "이기사",
      department: "설비보전팀",
      position: "사원",
    },
    status: "scheduled",
    priority: "high",
    createdAt: "2024-05-28T09:15:00Z",
    updatedAt: "2024-05-28T09:15:00Z",
    createdBy: "admin",
    updatedBy: "admin",
    recurrencePattern: "weekly",
  },
  {
    id: "4",
    standardId: "1",
    standard: {
      id: "1",
      name: "압축기 일일점검",
      version: "1.2",
      type: "daily",
    },
    equipmentId: "1",
    equipment: {
      id: "1",
      code: "COMP-A1-001",
      name: "공기압축기 #1",
      location: "A동 1층",
      department: "생산1팀",
    },
    scheduledDate: getDate(-1),
    scheduledTime: "09:00",
    estimatedDuration: 30,
    assignedToId: "1",
    assignedTo: {
      id: "1",
      name: "김기술",
      department: "설비보전팀",
      position: "주임",
    },
    status: "completed",
    priority: "medium",
    completedDate: getDate(-1),
    completedTime: "09:25",
    completedById: "1",
    completedBy: {
      id: "1",
      name: "김기술",
      department: "설비보전팀",
      position: "주임",
    },
    notes: "정상 작동 확인, 오일 레벨 정상",
    createdAt: "2024-05-25T10:00:00Z",
    updatedAt: "2024-06-02T09:25:00Z",
    createdBy: "admin",
    updatedBy: "user1",
    recurrencePattern: "daily",
  },
  {
    id: "5",
    standardId: "4",
    standard: {
      id: "4",
      name: "전기모터 분기점검",
      version: "1.0",
      type: "quarterly",
    },
    equipmentId: "2",
    equipment: {
      id: "2",
      code: "FAN-B2-002",
      name: "배기팬 #2",
      location: "B동 2층",
      department: "생산2팀",
    },
    scheduledDate: getDate(-18),
    scheduledTime: "11:00",
    estimatedDuration: 120,
    assignedToId: "2",
    assignedTo: {
      id: "2",
      name: "박엔지니어",
      department: "설비보전팀",
      position: "대리",
    },
    status: "missed",
    priority: "medium",
    createdAt: "2024-04-01T14:00:00Z",
    updatedAt: "2024-05-16T09:00:00Z",
    createdBy: "admin",
    updatedBy: "system",
    recurrencePattern: "quarterly",
  },
  {
    id: "6",
    standardId: "5",
    standard: {
      id: "5",
      name: "비상발전기 월간점검",
      version: "2.0",
      type: "monthly",
    },
    equipmentId: "4",
    equipment: {
      id: "4",
      code: "GEN-D1-004",
      name: "비상발전기 #1",
      location: "D동 지하1층",
      department: "시설팀",
    },
    scheduledDate: getDate(0),
    scheduledTime: "13:00",
    estimatedDuration: 90,
    assignedToId: "4",
    assignedTo: {
      id: "4",
      name: "최시설",
      department: "시설팀",
      position: "과장",
    },
    status: "in-progress",
    priority: "critical",
    createdAt: "2024-05-20T10:00:00Z",
    updatedAt: "2024-06-03T13:05:00Z",
    createdBy: "admin",
    updatedBy: "user4",
    recurrencePattern: "monthly",
  },
  {
    id: "7",
    standardId: "6",
    standard: {
      id: "6",
      name: "보일러 주간점검",
      version: "1.3",
      type: "weekly",
    },
    equipmentId: "5",
    equipment: {
      id: "5",
      code: "BOIL-D2-005",
      name: "보일러 #2",
      location: "D동 2층",
      department: "시설팀",
    },
    scheduledDate: getDate(4),
    scheduledTime: "15:00",
    estimatedDuration: 60,
    assignedToId: "5",
    assignedTo: {
      id: "5",
      name: "정보일러",
      department: "시설팀",
      position: "주임",
    },
    status: "scheduled",
    priority: "high",
    createdAt: "2024-05-31T09:00:00Z",
    updatedAt: "2024-05-31T09:00:00Z",
    createdBy: "admin",
    updatedBy: "admin",
    recurrencePattern: "weekly",
  },
  {
    id: "8",
    standardId: "7",
    standard: {
      id: "7",
      name: "에어컨 필터 교체",
      version: "1.0",
      type: "monthly",
    },
    equipmentId: "6",
    equipment: {
      id: "6",
      code: "AC-E3-006",
      name: "중앙공조기 #1",
      location: "E동 3층",
      department: "시설팀",
    },
    scheduledDate: getDate(-14),
    scheduledTime: "10:00",
    estimatedDuration: 45,
    assignedToId: "4",
    assignedTo: {
      id: "4",
      name: "최시설",
      department: "시설팀",
      position: "과장",
    },
    status: "rescheduled",
    priority: "medium",
    notes: "부품 미입고로 인한 일정 변경",
    createdAt: "2024-04-25T11:00:00Z",
    updatedAt: "2024-05-19T14:00:00Z",
    createdBy: "admin",
    updatedBy: "user4",
    recurrencePattern: "monthly",
    recurrenceEndDate: "2024-12-31",
  },
  {
    id: "9",
    standardId: "8",
    standard: {
      id: "8",
      name: "크레인 안전점검",
      version: "2.1",
      type: "daily",
    },
    equipmentId: "7",
    equipment: {
      id: "7",
      code: "CRANE-F1-007",
      name: "천장크레인 10톤",
      location: "F동 1층",
      department: "생산3팀",
    },
    scheduledDate: getDate(0),
    scheduledTime: "08:00",
    estimatedDuration: 20,
    assignedToId: "6",
    assignedTo: {
      id: "6",
      name: "강안전",
      department: "안전관리팀",
      position: "대리",
    },
    status: "completed",
    priority: "critical",
    completedDate: getDate(0),
    completedTime: "08:15",
    completedById: "6",
    completedBy: {
      id: "6",
      name: "강안전",
      department: "안전관리팀",
      position: "대리",
    },
    notes: "와이어로프 마모 발견, 교체 필요",
    createdAt: "2024-06-02T17:00:00Z",
    updatedAt: "2024-06-03T08:15:00Z",
    createdBy: "admin",
    updatedBy: "user6",
    recurrencePattern: "daily",
  },
  {
    id: "10",
    standardId: "9",
    standard: {
      id: "9",
      name: "지게차 월간점검",
      version: "1.1",
      type: "monthly",
    },
    equipmentId: "8",
    equipment: {
      id: "8",
      code: "FORK-G1-008",
      name: "전동지게차 #3",
      location: "G동 1층",
      department: "물류팀",
    },
    scheduledDate: getDate(12),
    scheduledTime: "16:00",
    estimatedDuration: 60,
    assignedToId: "7",
    assignedTo: {
      id: "7",
      name: "송물류",
      department: "물류팀",
      position: "사원",
    },
    status: "scheduled",
    priority: "medium",
    createdAt: "2024-05-31T10:30:00Z",
    updatedAt: "2024-05-31T10:30:00Z",
    createdBy: "admin",
    updatedBy: "admin",
    recurrencePattern: "monthly",
  },
  {
    id: "11",
    standardId: "10",
    standard: {
      id: "10",
      name: "컨베이어 벨트 점검",
      version: "1.0",
      type: "weekly",
    },
    equipmentId: "9",
    equipment: {
      id: "9",
      code: "CONV-H1-009",
      name: "컨베이어 #5",
      location: "H동 1층",
      department: "생산4팀",
    },
    scheduledDate: getDate(1),
    scheduledTime: "11:30",
    estimatedDuration: 40,
    assignedToId: "8",
    assignedTo: {
      id: "8",
      name: "한생산",
      department: "생산4팀",
      position: "주임",
    },
    status: "scheduled",
    priority: "high",
    createdAt: "2024-05-30T09:45:00Z",
    updatedAt: "2024-05-30T09:45:00Z",
    createdBy: "admin",
    updatedBy: "admin",
    recurrencePattern: "weekly",
  },
  {
    id: "12",
    standardId: "11",
    standard: {
      id: "11",
      name: "로봇 암 정밀점검",
      version: "2.3",
      type: "monthly",
    },
    equipmentId: "10",
    equipment: {
      id: "10",
      code: "ROBOT-I2-010",
      name: "용접 로봇 #2",
      location: "I동 2층",
      department: "자동화팀",
    },
    scheduledDate: getDate(-7),
    scheduledTime: "09:30",
    estimatedDuration: 180,
    assignedToId: "9",
    assignedTo: {
      id: "9",
      name: "임로봇",
      department: "자동화팀",
      position: "차장",
    },
    status: "canceled",
    priority: "high",
    notes: "설비 교체 예정으로 점검 취소",
    createdAt: "2024-05-15T13:20:00Z",
    updatedAt: "2024-05-25T10:15:00Z",
    createdBy: "admin",
    updatedBy: "user9",
    recurrencePattern: "monthly",
  },
  {
    id: "13",
    standardId: "12",
    standard: {
      id: "12",
      name: "전기배선 안전점검",
      version: "1.5",
      type: "quarterly",
    },
    equipmentId: "11",
    equipment: {
      id: "11",
      code: "ELEC-J3-011",
      name: "배전반 #3",
      location: "J동 3층",
      department: "전기팀",
    },
    scheduledDate: getDate(21),
    scheduledTime: "14:30",
    estimatedDuration: 120,
    assignedToId: "10",
    assignedTo: {
      id: "10",
      name: "오전기",
      department: "전기팀",
      position: "과장",
    },
    status: "scheduled",
    priority: "critical",
    createdAt: "2024-05-10T11:00:00Z",
    updatedAt: "2024-05-10T11:00:00Z",
    createdBy: "admin",
    updatedBy: "admin",
    recurrencePattern: "quarterly",
  },
  {
    id: "14",
    standardId: "13",
    standard: {
      id: "13",
      name: "소화설비 점검",
      version: "2.0",
      type: "monthly",
    },
    equipmentId: "12",
    equipment: {
      id: "12",
      code: "FIRE-K1-012",
      name: "스프링클러 시스템",
      location: "전체 건물",
      department: "안전관리팀",
    },
    scheduledDate: getDate(5),
    scheduledTime: "10:00",
    estimatedDuration: 240,
    assignedToId: "6",
    assignedTo: {
      id: "6",
      name: "강안전",
      department: "안전관리팀",
      position: "대리",
    },
    status: "scheduled",
    priority: "critical",
    createdAt: "2024-05-28T16:30:00Z",
    updatedAt: "2024-05-28T16:30:00Z",
    createdBy: "admin",
    updatedBy: "admin",
    recurrencePattern: "monthly",
  },
  {
    id: "15",
    standardId: "14",
    standard: {
      id: "14",
      name: "CNC 기계 정밀점검",
      version: "3.1",
      type: "weekly",
    },
    equipmentId: "13",
    equipment: {
      id: "13",
      code: "CNC-L2-013",
      name: "CNC 밀링머신 #4",
      location: "L동 2층",
      department: "가공팀",
    },
    scheduledDate: getDate(-2),
    scheduledTime: "15:30",
    estimatedDuration: 90,
    assignedToId: "11",
    assignedTo: {
      id: "11",
      name: "조가공",
      department: "가공팀",
      position: "대리",
    },
    status: "completed",
    priority: "medium",
    completedDate: getDate(-2),
    completedTime: "17:15",
    completedById: "11",
    completedBy: {
      id: "11",
      name: "조가공",
      department: "가공팀",
      position: "대리",
    },
    notes: "공구 교체 완료, 정밀도 테스트 통과",
    createdAt: "2024-05-20T09:00:00Z",
    updatedAt: "2024-06-01T17:15:00Z",
    createdBy: "admin",
    updatedBy: "user11",
    recurrencePattern: "weekly",
  },
  {
    id: "16",
    standardId: "15",
    standard: {
      id: "15",
      name: "냉동창고 온도점검",
      version: "1.0",
      type: "daily",
    },
    equipmentId: "14",
    equipment: {
      id: "14",
      code: "COLD-M1-014",
      name: "냉동창고 #2",
      location: "M동 1층",
      department: "물류팀",
    },
    scheduledDate: getDate(0),
    scheduledTime: "07:00",
    estimatedDuration: 15,
    assignedToId: "7",
    assignedTo: {
      id: "7",
      name: "송물류",
      department: "물류팀",
      position: "사원",
    },
    status: "completed",
    priority: "high",
    completedDate: getDate(0),
    completedTime: "07:10",
    completedById: "7",
    completedBy: {
      id: "7",
      name: "송물류",
      department: "물류팀",
      position: "사원",
    },
    notes: "온도 -18°C 유지 중, 정상",
    createdAt: "2024-05-31T16:00:00Z",
    updatedAt: "2024-06-03T07:10:00Z",
    createdBy: "admin",
    updatedBy: "user7",
    recurrencePattern: "daily",
  },
  {
    id: "17",
    standardId: "16",
    standard: {
      id: "16",
      name: "태양광 패널 점검",
      version: "1.2",
      type: "monthly",
    },
    equipmentId: "15",
    equipment: {
      id: "15",
      code: "SOLAR-N0-015",
      name: "태양광 발전설비",
      location: "옥상",
      department: "시설팀",
    },
    scheduledDate: getDate(9),
    scheduledTime: "13:30",
    estimatedDuration: 120,
    assignedToId: "4",
    assignedTo: {
      id: "4",
      name: "최시설",
      department: "시설팀",
      position: "과장",
    },
    status: "scheduled",
    priority: "medium",
    createdAt: "2024-05-25T11:30:00Z",
    updatedAt: "2024-05-25T11:30:00Z",
    createdBy: "admin",
    updatedBy: "admin",
    recurrencePattern: "monthly",
  },
  {
    id: "18",
    standardId: "17",
    standard: {
      id: "17",
      name: "폐수처리장치 점검",
      version: "2.5",
      type: "weekly",
    },
    equipmentId: "16",
    equipment: {
      id: "16",
      code: "WASTE-P0-016",
      name: "폐수처리시설",
      location: "P동 지하",
      department: "환경안전팀",
    },
    scheduledDate: getDate(3),
    scheduledTime: "09:00",
    estimatedDuration: 60,
    assignedToId: "12",
    assignedTo: {
      id: "12",
      name: "윤환경",
      department: "환경안전팀",
      position: "과장",
    },
    status: "scheduled",
    priority: "high",
    createdAt: "2024-05-29T14:00:00Z",
    updatedAt: "2024-05-29T14:00:00Z",
    createdBy: "admin",
    updatedBy: "admin",
    recurrencePattern: "weekly",
  },
  {
    id: "19",
    standardId: "18",
    standard: {
      id: "18",
      name: "지게차 배터리 점검",
      version: "1.0",
      type: "weekly",
    },
    equipmentId: "8",
    equipment: {
      id: "8",
      code: "FORK-G1-008",
      name: "전동지게차 #3",
      location: "G동 1층",
      department: "물류팀",
    },
    scheduledDate: getDate(-5),
    scheduledTime: "17:00",
    estimatedDuration: 30,
    assignedToId: "7",
    assignedTo: {
      id: "7",
      name: "송물류",
      department: "물류팀",
      position: "사원",
    },
    status: "completed",
    priority: "medium",
    completedDate: getDate(-5),
    completedTime: "17:25",
    completedById: "7",
    completedBy: {
      id: "7",
      name: "송물류",
      department: "물류팀",
      position: "사원",
    },
    notes: "배터리 충전 상태 양호",
    createdAt: "2024-05-20T10:00:00Z",
    updatedAt: "2024-05-29T17:25:00Z",
    createdBy: "admin",
    updatedBy: "user7",
    recurrencePattern: "weekly",
  },
  {
    id: "20",
    standardId: "19",
    standard: {
      id: "19",
      name: "에어 컴프레서 오일 교체",
      version: "1.1",
      type: "quarterly",
    },
    equipmentId: "1",
    equipment: {
      id: "1",
      code: "COMP-A1-001",
      name: "공기압축기 #1",
      location: "A동 1층",
      department: "생산1팀",
    },
    scheduledDate: getDate(30),
    scheduledTime: "08:30",
    estimatedDuration: 120,
    assignedToId: "1",
    assignedTo: {
      id: "1",
      name: "김기술",
      department: "설비보전팀",
      position: "주임",
    },
    status: "scheduled",
    priority: "medium",
    createdAt: "2024-05-15T13:00:00Z",
    updatedAt: "2024-05-15T13:00:00Z",
    createdBy: "admin",
    updatedBy: "admin",
    recurrencePattern: "quarterly",
  },
]
