import type {
  MaintenanceRequest,
  MaintenancePlan,
  MaintenanceWork,
  EquipmentListItem,
  MaintenanceUser,
  MaintenanceTeam,
} from "@fms/types"

export const mockEquipmentList: EquipmentListItem[] = [
  { id: "1", name: "컨베이어 #1 (EQ-CONV-001)", code: "EQ-CONV-001", location: "A동 1층" },
  { id: "2", name: "압축기 #1 (EQ-COMP-001)", code: "EQ-COMP-001", location: "B동 지하1층" },
  { id: "3", name: "펌프 #1 (EQ-PUMP-001)", code: "EQ-PUMP-001", location: "A동 2층" },
  { id: "4", name: "로봇 #1 (EQ-ROBOT-001)", code: "EQ-ROBOT-001", location: "C동 1층" },
  { id: "5", name: "크레인 #1 (EQ-CRANE-001)", code: "EQ-CRANE-001", location: "D동 전체" },
  { id: "6", name: "선반 #1 (EQ-LATHE-001)", code: "EQ-LATHE-001", location: "공작실" },
  { id: "7", name: "밀링머신 #1 (EQ-MILL-001)", code: "EQ-MILL-001", location: "공작실" },
  { id: "8", name: "보일러 #1 (EQ-BOIL-001)", code: "EQ-BOIL-001", location: "기계실" },
  { id: "9", name: "공조기 #1 (EQ-HVAC-001)", code: "EQ-HVAC-001", location: "옥상" },
  { id: "10", name: "변압기 #1 (EQ-TRANS-001)", code: "EQ-TRANS-001", location: "전기실" },
]

export const mockMaintenanceRequests: MaintenanceRequest[] = [
  {
    id: "1",
    requestNo: "REQ-2024-001",
    title: "컨베이어 벨트 교체 요청",
    description: "컨베이어 벨트에 균열이 발생하여 교체가 필요합니다.",
    equipmentId: "1",
    equipmentCode: "EQ-CONV-001",
    equipmentName: "컨베이어 #1",
    requestType: "repair", // Changed from workType to requestType for clarity
    workType: "replace", // This can be derived or set during planning
    requesterName: "김작업",
    requestDate: "2024-01-15T09:00:00Z",
    priority: "high",
    status: "approved", // Assuming it's approved to be planned
    requestedBy: "user1",
    approvedBy: "user2",
    approvedByName: "이관리",
    approvalDate: "2024-01-15T10:30:00Z",
    estimatedDuration: 4,
    estimatedCost: 500000,
    location: "A동 1층",
    department: "생산1팀",
    isActive: true,
    createdAt: "2024-01-15T09:00:00Z",
    updatedAt: "2024-01-15T10:30:00Z",
    createdBy: "user1",
    updatedBy: "user2",
  },
  {
    id: "2",
    requestNo: "REQ-2024-002",
    title: "압축기 정기점검",
    description: "월간 정기점검 일정에 따른 압축기 점검",
    equipmentId: "2",
    equipmentCode: "EQ-COMP-001",
    equipmentName: "압축기 #1",
    requestType: "inspection",
    workType: "inspect",
    requesterName: "시스템",
    requestDate: "2024-01-10T00:00:00Z",
    priority: "normal",
    status: "planned", // Already planned
    requestedBy: "system",
    approvedBy: "user2",
    approvedByName: "이관리",
    approvalDate: "2024-01-10T08:00:00Z",
    estimatedDuration: 2,
    estimatedCost: 100000,
    location: "B동 지하1층",
    department: "설비관리팀",
    isActive: true,
    createdAt: "2024-01-10T00:00:00Z",
    updatedAt: "2024-01-10T08:00:00Z",
    createdBy: "system",
    updatedBy: "user2",
  },
  {
    id: "3",
    requestNo: "REQ-2024-003",
    title: "로봇 암 수리",
    description: "로봇 암 관절부에서 이상음 발생",
    equipmentId: "4",
    equipmentCode: "EQ-ROBOT-001",
    equipmentName: "로봇 #1",
    requestType: "repair",
    workType: "repair",
    requesterName: "박운영",
    requestDate: "2024-01-20T14:30:00Z",
    priority: "critical",
    status: "in_progress", // Already in progress
    requestedBy: "user3",
    approvedBy: "user2",
    approvedByName: "이관리",
    approvalDate: "2024-01-20T15:00:00Z",
    estimatedDuration: 6,
    estimatedCost: 800000,
    location: "C동 1층",
    department: "생산2팀",
    isActive: true,
    createdAt: "2024-01-20T14:30:00Z",
    updatedAt: "2024-01-20T15:00:00Z",
    createdBy: "user3",
    updatedBy: "user2",
  },
  {
    id: "4",
    requestNo: "REQ-2024-004",
    title: "펌프 성능 개선",
    description: "펌프 효율 향상을 위한 개선 작업",
    equipmentId: "3",
    equipmentCode: "EQ-PUMP-001",
    equipmentName: "펌프 #1",
    requestType: "improvement",
    workType: "upgrade",
    requesterName: "정개선",
    requestDate: "2024-01-22T11:00:00Z",
    priority: "normal",
    status: "requested",
    requestedBy: "user4",
    estimatedDuration: 8,
    estimatedCost: 1200000,
    location: "A동 2층",
    department: "생산1팀",
    isActive: true,
    createdAt: "2024-01-22T11:00:00Z",
    updatedAt: "2024-01-22T11:00:00Z",
    createdBy: "user4",
    updatedBy: "user4",
  },
  {
    id: "5",
    requestNo: "REQ-2024-005",
    title: "크레인 비상수리",
    description: "크레인 브레이크 시스템 고장으로 비상수리 필요",
    equipmentId: "5",
    equipmentCode: "EQ-CRANE-001",
    equipmentName: "크레인 #1",
    requestType: "emergency_repair",
    workType: "repair",
    requesterName: "조안전",
    requestDate: "2024-01-18T16:45:00Z",
    priority: "critical",
    status: "completed",
    requestedBy: "user5",
    approvedBy: "user2",
    approvedByName: "이관리",
    approvalDate: "2024-01-18T17:00:00Z",
    estimatedDuration: 3,
    estimatedCost: 600000,
    location: "D동 전체",
    department: "설비관리팀",
    isActive: true,
    createdAt: "2024-01-18T16:45:00Z",
    updatedAt: "2024-01-19T20:00:00Z",
    createdBy: "user5",
    updatedBy: "user6",
  },
]

export const mockMaintenancePlans: MaintenancePlan[] = [
  {
    id: "MPLAN-001", // Changed for consistency
    requestId: "1",
    planNo: "PLAN-2024-001",
    title: "컨베이어 벨트 교체 작업",
    description: "기존 벨트 제거 후 신규 벨트 설치 및 정렬 조정",
    equipmentId: "1",
    equipmentCode: "EQ-CONV-001",
    equipmentName: "컨베이어 #1",
    workType: "replace",
    priority: "high",
    status: "assigned",
    plannedBy: "user2",
    plannedByName: "이관리",
    planDate: "2024-01-15T11:00:00Z",
    scheduledStartDate: "2024-01-16T08:00:00Z",
    scheduledEndDate: "2024-01-16T12:00:00Z",
    estimatedDuration: 4,
    estimatedCost: 500000,
    assignedTo: "user6",
    assignedToName: "강정비",
    assignedTeam: "maintenance-team-1",
    assignedTeamName: "정비1팀",
    assignDate: "2024-01-15T11:30:00Z",
    requesterName: "김작업",
    requestDate: "2024-01-15T09:00:00Z",
    materials: [
      {
        id: "1",
        materialId: "MAT-001",
        materialCode: "BELT-CV-100",
        materialName: "컨베이어 벨트 (100m)",
        quantity: 1,
        unit: "EA",
        unitCost: 400000,
        totalCost: 400000,
        isRequired: true,
      },
      {
        id: "2",
        materialId: "MAT-002",
        materialCode: "BOLT-M8-50",
        materialName: "볼트 M8x50",
        quantity: 20,
        unit: "EA",
        unitCost: 500,
        totalCost: 10000,
        isRequired: true,
      },
    ],
    procedures: [
      {
        id: "1",
        step: 1,
        title: "작업 준비",
        description: "작업구역 안전 확보 및 도구 준비",
        estimatedDuration: 30,
        safetyNotes: "작업구역 출입 통제, 안전장비 착용",
      },
      {
        id: "2",
        step: 2,
        title: "기존 벨트 제거",
        description: "기존 컨베이어 벨트 분해 및 제거",
        estimatedDuration: 90,
        safetyNotes: "전원 차단 확인, 회전부 주의",
      },
      {
        id: "3",
        step: 3,
        title: "신규 벨트 설치",
        description: "새로운 컨베이어 벨트 설치 및 연결",
        estimatedDuration: 120,
        safetyNotes: "벨트 장력 조절 시 협착 주의",
      },
      {
        id: "4",
        step: 4,
        title: "정렬 및 테스트",
        description: "벨트 정렬 조정 및 시운전",
        estimatedDuration: 60,
        safetyNotes: "시운전 중 안전거리 유지",
      },
    ],
    safetyNotes: "고소작업이므로 안전벨트 착용 필수. 작업 전 전원 차단 확인.",
    specialInstructions: "벨트 설치 후 24시간 길들이기 운전 필요",
    location: "A동 1층",
    department: "생산1팀",
    isActive: true,
    createdAt: "2024-01-15T11:00:00Z",
    updatedAt: "2024-01-15T11:30:00Z",
    createdBy: "user2",
    updatedBy: "user2",
  },
  {
    id: "MPLAN-002", // Changed for consistency
    requestId: "2",
    planNo: "PLAN-2024-002",
    title: "압축기 정기점검 작업",
    description: "압축기 전체 시스템 점검 및 오일 교체",
    equipmentId: "2",
    equipmentCode: "EQ-COMP-001",
    equipmentName: "압축기 #1",
    workType: "inspect",
    priority: "normal",
    status: "planned",
    plannedBy: "user2",
    plannedByName: "이관리",
    planDate: "2024-01-10T08:30:00Z",
    scheduledStartDate: "2024-01-25T09:00:00Z",
    scheduledEndDate: "2024-01-25T11:00:00Z",
    estimatedDuration: 2,
    estimatedCost: 100000,
    requesterName: "시스템",
    requestDate: "2024-01-10T00:00:00Z",
    materials: [
      {
        id: "3",
        materialId: "MAT-003",
        materialCode: "OIL-COMP-46",
        materialName: "압축기 오일 (20L)",
        quantity: 1,
        unit: "EA",
        unitCost: 80000,
        totalCost: 80000,
        isRequired: true,
      },
    ],
    procedures: [
      {
        id: "5",
        step: 1,
        title: "외관 점검",
        description: "압축기 외관 및 배관 누유 점검",
        estimatedDuration: 15,
        safetyNotes: "고온 부위 접촉 주의",
      },
      {
        id: "6",
        step: 2,
        title: "오일 교체",
        description: "기존 오일 배출 후 신규 오일 주입",
        estimatedDuration: 45,
        safetyNotes: "폐오일 적정 처리 필요",
      },
      {
        id: "7",
        step: 3,
        title: "성능 테스트",
        description: "압력, 온도, 진동 측정",
        estimatedDuration: 30,
        safetyNotes: "측정 중 안전거리 유지",
      },
    ],
    safetyNotes: "압축기 정지 후 충분한 냉각 시간 확보",
    location: "B동 지하1층",
    department: "설비관리팀",
    isActive: true,
    createdAt: "2024-01-10T08:30:00Z",
    updatedAt: "2024-01-10T08:30:00Z",
    createdBy: "user2",
    updatedBy: "user2",
  },
  {
    id: "MPLAN-003",
    requestId: "REQ-2024-00X", // Example, assuming a request
    planNo: "PLAN-2024-003",
    title: "펌프 #1 베어링 교체",
    description: "펌프 #1 소음 발생으로 인한 베어링 교체 계획",
    equipmentId: "3",
    equipmentCode: "EQ-PUMP-001",
    equipmentName: "펌프 #1",
    workType: "replace",
    priority: "high",
    status: "planned",
    plannedBy: "user2",
    plannedByName: "이관리",
    planDate: "2024-06-10T10:00:00Z",
    scheduledStartDate: "2024-06-15T09:00:00Z",
    scheduledEndDate: "2024-06-15T17:00:00Z",
    estimatedDuration: 8,
    estimatedCost: 350000,
    requesterName: "최생산",
    requestDate: "2024-06-08T14:00:00Z",
    materials: [],
    procedures: [],
    location: "A동 2층",
    department: "생산1팀",
    isActive: true,
    createdAt: "2024-06-10T10:00:00Z",
    updatedAt: "2024-06-10T10:00:00Z",
    createdBy: "user2",
    updatedBy: "user2",
  },
]

export const mockMaintenanceWorks: MaintenanceWork[] = [
  {
    id: "MWORK-001",
    planId: "MPLAN-001", // Linked to a plan
    requestId: "1", // Original request
    workNo: "W2024001",
    title: "본관 에어컨 필터 교체 (정기)",
    description: "본관 전체 에어컨 필터 교체 및 내부 청소",
    equipmentId: "EQ-AC-001",
    equipmentName: "본관 중앙 에어컨",
    workType: "replace",
    priority: "normal",
    status: "pending",
    assignedTo: "user6",
    assignedToName: "강정비",
    assignedTeam: "maintenance-team-1",
    assignedTeamName: "정비1팀",
    assignDate: "2024-05-20T09:00:00Z",
    createdAt: "2024-05-15T10:00:00Z",
    updatedAt: "2024-05-20T09:00:00Z",
    createdBy: "system",
    location: "본관 전체",
    department: "시설관리팀",
    isActive: true,
  },
  {
    id: "MWORK-002",
    planId: "MPLAN-002", // Linked to a plan
    requestId: "2", // Original request
    workNo: "W2024002",
    title: "생산1라인 프레스 유압 점검",
    description: "정기 유압 시스템 점검 및 오일 보충",
    equipmentId: "EQ-PRESS-003",
    equipmentName: "3번 프레스 (생산1라인)",
    workType: "inspect",
    priority: "high",
    status: "in_progress",
    assignedTo: "user7",
    assignedToName: "김기술",
    assignedTeam: "maintenance-team-2",
    assignedTeamName: "정비2팀",
    assignDate: "2024-05-21T09:00:00Z",
    startDate: "2024-05-22T10:00:00Z",
    createdAt: "2024-05-18T11:00:00Z",
    updatedAt: "2024-05-22T10:00:00Z",
    location: "생산1라인",
    department: "생산1팀",
    isActive: true,
  },
  {
    id: "MWORK-003",
    planId: "MPLAN-00X", // Assuming a plan existed
    requestId: "5", // Linked to request REQ-2024-005
    workNo: "WORK-2024-002", // From original mock
    title: "크레인 브레이크 비상수리",
    description: "크레인 브레이크 패드 교체 및 유압 시스템 점검",
    equipmentId: "5",
    equipmentCode: "EQ-CRANE-001",
    equipmentName: "크레인 #1",
    workType: "repair",
    priority: "critical",
    status: "completed",
    assignedTo: "user8",
    assignedToName: "박수리",
    assignedTeam: "maintenance-team-1",
    assignedTeamName: "정비1팀",
    assignDate: "2024-01-18T17:30:00Z",
    startDate: "2024-01-18T18:00:00Z",
    endDate: "2024-01-19T20:00:00Z",
    actualDuration: 3, // hours
    actualCost: 580000,
    workResults: [
      {
        id: "4",
        procedureId: "11", // Placeholder
        step: 1,
        title: "크레인 안전 정지",
        description: "크레인 완전 정지 및 안전 조치",
        result: "completed",
        notes: "정상 완료",
        duration: 10, // minutes
        completedBy: "user8",
        completedByName: "박수리",
        completedAt: "2024-01-18T18:10:00Z",
      },
    ],
    materialsUsed: [
      {
        id: "2",
        materialId: "MAT-005",
        materialCode: "BRAKE-PAD-CR50",
        materialName: "크레인 브레이크 패드",
        plannedQuantity: 4,
        actualQuantity: 4,
        unit: "EA",
        unitCost: 120000,
        totalCost: 480000,
        warehouseId: "WH-001",
        warehouseName: "중앙창고",
        usedBy: "user8",
        usedByName: "박수리",
        usedAt: "2024-01-18T19:30:00Z",
      },
    ],
    completionNotes: "브레이크 패드 완전 교체 완료. 안전 테스트 정상. 다음 점검일: 3개월 후",
    nextMaintenanceDate: "2024-04-18",
    location: "D동 전체",
    department: "설비관리팀",
    isActive: true,
    createdAt: "2024-01-18T17:30:00Z",
    updatedAt: "2024-01-19T20:00:00Z",
    createdBy: "user2",
    updatedBy: "user8",
  },
  {
    id: "MWORK-004",
    planId: "MPLAN-00Y", // Assuming a plan
    workNo: "W2024004",
    title: "서버실 UPS 점검",
    description: "서버실 무정전 전원 공급 장치(UPS) 정기 점검 및 배터리 상태 확인.",
    equipmentId: "EQ-SERVER-UPS-001",
    equipmentName: "서버실 UPS #1",
    workType: "inspect",
    priority: "high",
    status: "pending",
    assignedTo: "user7",
    assignedToName: "김기술",
    assignedTeam: "maintenance-team-2",
    assignedTeamName: "정비2팀",
    assignDate: "2024-06-01T09:00:00Z",
    createdAt: "2024-05-28T16:00:00Z",
    updatedAt: "2024-06-01T09:00:00Z",
    createdBy: "system",
    location: "서버실",
    department: "IT팀",
    isActive: true,
  },
]

export const mockMaintenanceUsers: MaintenanceUser[] = [
  { id: "user1", name: "김요청", teamId: "production-team-1", teamName: "생산1팀" },
  { id: "user2", name: "이관리", teamId: "facility-management", teamName: "설비관리팀" },
  { id: "user3", name: "박운영", teamId: "production-team-2", teamName: "생산2팀" },
  { id: "user4", name: "정개선", teamId: "production-team-1", teamName: "생산1팀" },
  { id: "user5", name: "조안전", teamId: "safety-team", teamName: "안전팀" },
  { id: "user6", name: "강정비", teamId: "maintenance-team-1", teamName: "정비1팀" },
  { id: "user7", name: "김기술", teamId: "maintenance-team-2", teamName: "정비2팀" },
  { id: "user8", name: "박수리", teamId: "maintenance-team-1", teamName: "정비1팀" },
  { id: "user9", name: "이전기", teamId: "electrical-team", teamName: "전기팀" },
  { id: "user10", name: "조기계", teamId: "mechanical-team", teamName: "기계팀" },
]

export const mockMaintenanceTeams: MaintenanceTeam[] = [
  { id: "maintenance-team-1", name: "정비1팀", description: "기계 설비 정비 담당" },
  { id: "maintenance-team-2", name: "정비2팀", description: "전기 및 자동화 설비 정비 담당" },
  { id: "electrical-team", name: "전기팀", description: "고압 및 저압 전기 설비 전문" },
  { id: "mechanical-team", name: "기계팀", description: "회전기기 및 유공압 설비 전문" },
  { id: "facility-management", name: "설비관리팀", description: "설비 전반 관리 및 계획" },
  { id: "production-team-1", name: "생산1팀", description: "A라인 생산 담당" },
  { id: "production-team-2", name: "생산2팀", description: "B라인 생산 담당" },
  { id: "safety-team", name: "안전팀", description: "작업장 안전 관리" },
]
