import type { MaterialStock, Warehouse, StockAdjustment } from "@fms/types"

export const mockWarehouses: Warehouse[] = [
  {
    id: "WH001",
    code: "WH-A",
    name: "중앙창고",
    location: "A동 1층",
    manager: "김창고",
    capacity: 1000,
    currentUtilization: 75,
    status: "active",
    createdAt: "2024-01-01",
  },
  {
    id: "WH002",
    code: "WH-B",
    name: "부품창고",
    location: "B동 지하1층",
    manager: "이부품",
    capacity: 500,
    currentUtilization: 60,
    status: "active",
    createdAt: "2024-01-01",
  },
  {
    id: "WH003",
    code: "WH-C",
    name: "소모품창고",
    location: "C동 2층",
    manager: "박소모",
    capacity: 300,
    currentUtilization: 85,
    status: "active",
    createdAt: "2024-01-01",
  },
]

export const mockMaterialStocks: MaterialStock[] = [
  {
    id: "MS001",
    materialId: "MAT001",
    materialCode: "CON-MEC-001",
    materialName: "볼베어링 6205",
    warehouseId: "WH001",
    warehouseName: "중앙창고",
    location: "A-01-01",
    currentStock: 150,
    safetyStock: 50,
    minStock: 30,
    maxStock: 200,
    unit: "EA",
    unitPrice: 15000,
    totalValue: 2250000,
    lastUpdated: "2024-12-03",
    status: "normal",
  },
  {
    id: "MS002",
    materialId: "MAT002",
    materialCode: "REP-ELE-001",
    materialName: "3상 유도전동기 5HP",
    warehouseId: "WH002",
    warehouseName: "부품창고",
    location: "B-02-05",
    currentStock: 5,
    safetyStock: 10,
    minStock: 5,
    maxStock: 20,
    unit: "EA",
    unitPrice: 850000,
    totalValue: 4250000,
    lastUpdated: "2024-12-02",
    status: "low",
  },
  {
    id: "MS003",
    materialId: "MAT003",
    materialCode: "CON-CHE-001",
    materialName: "유압오일 VG46",
    warehouseId: "WH003",
    warehouseName: "소모품창고",
    location: "C-01-03",
    currentStock: 0,
    safetyStock: 20,
    minStock: 10,
    maxStock: 100,
    unit: "L",
    unitPrice: 8500,
    totalValue: 0,
    lastUpdated: "2024-12-01",
    status: "out",
  },
  {
    id: "MS004",
    materialId: "MAT004",
    materialCode: "SPA-MEC-001",
    materialName: "체인 40B-1",
    warehouseId: "WH001",
    warehouseName: "중앙창고",
    location: "A-03-02",
    currentStock: 250,
    safetyStock: 50,
    minStock: 30,
    maxStock: 150,
    unit: "M",
    unitPrice: 12000,
    totalValue: 3000000,
    lastUpdated: "2024-12-03",
    status: "excess",
  },
]

export const mockStockAdjustments: StockAdjustment[] = [
  {
    id: "SA001",
    materialId: "MAT001",
    materialCode: "CON-MEC-001",
    materialName: "볼베어링 6205",
    warehouseId: "WH001",
    warehouseName: "중앙창고",
    adjustmentType: "increase",
    beforeQuantity: 120,
    afterQuantity: 150,
    adjustmentQuantity: 30,
    reason: "입고 누락분 반영",
    adjustedBy: "김재고",
    adjustedAt: "2024-12-03 09:30:00",
    approvedBy: "이승인",
    approvedAt: "2024-12-03 10:00:00",
    status: "approved",
  },
  {
    id: "SA002",
    materialId: "MAT002",
    materialCode: "REP-ELE-001",
    materialName: "3상 유도전동기 5HP",
    warehouseId: "WH002",
    warehouseName: "부품창고",
    adjustmentType: "decrease",
    beforeQuantity: 8,
    afterQuantity: 5,
    adjustmentQuantity: -3,
    reason: "불량품 폐기",
    adjustedBy: "박재고",
    adjustedAt: "2024-12-02 14:20:00",
    status: "pending",
  },
]
