import type { Organization } from "@fms/types"

export const mockOrganizations: Organization[] = [
  {
    id: "1",
    code: "ABC",
    name: "ABC 제조",
    type: "company",
    level: 1,
    sortOrder: 1,
    description: "ABC 제조 본사",
    isActive: true,
    createdAt: "2024-01-01T00:00:00Z",
    updatedAt: "2024-01-01T00:00:00Z",
    createdBy: "admin",
    updatedBy: "admin",
  },
  {
    id: "2",
    code: "ABC-PROD",
    name: "생산본부",
    type: "department",
    parentId: "1",
    parentName: "ABC 제조",
    level: 2,
    sortOrder: 1,
    description: "생산 관련 업무 총괄",
    isActive: true,
    createdAt: "2024-01-01T00:00:00Z",
    updatedAt: "2024-01-01T00:00:00Z",
    createdBy: "admin",
    updatedBy: "admin",
  },
  {
    id: "3",
    code: "ABC-PROD-1",
    name: "생산1팀",
    type: "team",
    parentId: "2",
    parentName: "생산본부",
    level: 3,
    sortOrder: 1,
    description: "A라인 생산 담당",
    isActive: true,
    createdAt: "2024-01-01T00:00:00Z",
    updatedAt: "2024-01-01T00:00:00Z",
    createdBy: "admin",
    updatedBy: "admin",
  },
  {
    id: "4",
    code: "ABC-PROD-2",
    name: "생산2팀",
    type: "team",
    parentId: "2",
    parentName: "생산본부",
    level: 3,
    sortOrder: 2,
    description: "B라인 생산 담당",
    isActive: true,
    createdAt: "2024-01-01T00:00:00Z",
    updatedAt: "2024-01-01T00:00:00Z",
    createdBy: "admin",
    updatedBy: "admin",
  },
  {
    id: "5",
    code: "ABC-MAINT",
    name: "설비관리팀",
    type: "department",
    parentId: "1",
    parentName: "ABC 제조",
    level: 2,
    sortOrder: 2,
    description: "설비 유지보수 및 관리",
    isActive: true,
    createdAt: "2024-01-01T00:00:00Z",
    updatedAt: "2024-01-01T00:00:00Z",
    createdBy: "admin",
    updatedBy: "admin",
  },
  {
    id: "6",
    code: "ABC-IT",
    name: "정보시스템팀",
    type: "department",
    parentId: "1",
    parentName: "ABC 제조",
    level: 2,
    sortOrder: 3,
    description: "IT 인프라 및 시스템 관리",
    isActive: true,
    createdAt: "2024-01-01T00:00:00Z",
    updatedAt: "2024-01-01T00:00:00Z",
    createdBy: "admin",
    updatedBy: "admin",
  },
]
