import { Sensor } from "@fms/types";

export const mockSensors: Sensor[] = [
  {
    id: "SNS-001",
    name: "1공장 A라인 온도",
    type: "temperature",
    group: "1공장",
    location: "1공장 A라인",
    status: "active",
    lastValue: 25.5,
    unit: "°C",
    lastUpdate: new Date().toISOString(),
    description: "1공장 A라인 온도 모니터링",
    connectionType: "wifi",
    ipAddress: "192.168.1.101",
    port: 502,
    pollingInterval: 10,
    isActive: true,
    createdAt: "2024-01-01T00:00:00Z",
    updatedAt: new Date().toISOString(),
  },
  {
    id: "SNS-002",
    name: "1공장 B라인 진동",
    type: "vibration",
    group: "1공장",
    location: "1공장 B라인",
    status: "warning",
    lastValue: 2.8,
    unit: "mm/s²",
    lastUpdate: new Date().toISOString(),
    description: "1공장 B라인 진동 모니터링",
    connectionType: "ethernet",
    ipAddress: "192.168.1.102",
    port: 502,
    pollingInterval: 5,
    isActive: true,
    createdAt: "2024-01-01T00:00:00Z",
    updatedAt: new Date().toISOString(),
  },
  {
    id: "SNS-003",
    name: "전기실 전력",
    type: "power",
    group: "전기실",
    location: "전기실",
    status: "active",
    lastValue: 150.2,
    unit: "kW",
    lastUpdate: new Date().toISOString(),
    description: "전기실 전력 모니터링",
    connectionType: "modbus",
    ipAddress: "192.168.1.103",
    port: 502,
    pollingInterval: 15,
    isActive: true,
    createdAt: "2024-01-01T00:00:00Z",
    updatedAt: new Date().toISOString(),
  },
  {
    id: "SNS-004",
    name: "본관 2층 온습도",
    type: "humidity",
    group: "본관",
    location: "본관 2층",
    status: "error",
    lastValue: 65.3,
    unit: "%",
    lastUpdate: new Date().toISOString(),
    description: "본관 2층 습도 모니터링",
    connectionType: "wifi",
    ipAddress: "192.168.1.104",
    port: 502,
    pollingInterval: 30,
    isActive: true,
    createdAt: "2024-01-01T00:00:00Z",
    updatedAt: new Date().toISOString(),
  },
  {
    id: "SNS-005",
    name: "2공장 창고 온도",
    type: "temperature",
    group: "2공장",
    location: "2공장 창고",
    status: "inactive",
    lastValue: 18.2,
    unit: "°C",
    lastUpdate: new Date().toISOString(),
    description: "2공장 창고 온도 모니터링",
    connectionType: "lora",
    ipAddress: "192.168.1.105",
    port: 502,
    pollingInterval: 60,
    isActive: false,
    createdAt: "2024-01-01T00:00:00Z",
    updatedAt: new Date().toISOString(),
  },
];
