import type { TPMTeam, TPMActivity } from "@fms/types"

export const mockTPMTeams: TPMTeam[] = [
  {
    id: "1",
    code: "TPM-TEAM-001",
    name: "설비개선 1팀",
    description: "컨베이어 라인 담당 TPM 분임조",
    department: "생산1팀",
    leader: "user1",
    leaderName: "김생산",
    members: [
      {
        id: "1",
        userId: "user1",
        userName: "김생산",
        department: "생산1팀",
        position: "팀장",
        role: "leader",
        joinDate: "2023-01-01",
        isActive: true,
      },
      {
        id: "2",
        userId: "user6",
        userName: "강정비",
        department: "정비1팀",
        position: "과장",
        role: "facilitator",
        joinDate: "2023-01-01",
        isActive: true,
      },
      {
        id: "3",
        userId: "user3",
        userName: "박운영",
        department: "생산2팀",
        position: "대리",
        role: "secretary",
        joinDate: "2023-01-01",
        isActive: true,
      },
      {
        id: "4",
        userId: "user4",
        userName: "정개선",
        department: "생산1팀",
        position: "사원",
        role: "member",
        joinDate: "2023-01-01",
        isActive: true,
      },
    ],
    equipmentArea: "A동 1층 컨베이어 라인",
    targetEquipments: ["1", "6", "7"],
    establishedDate: "2023-01-01",
    status: "active",
    meetingDay: "월요일",
    meetingTime: "16:00",
    meetingLocation: "A동 회의실",
    isActive: true,
    createdAt: "2023-01-01T00:00:00Z",
    updatedAt: "2023-01-01T00:00:00Z",
    createdBy: "admin",
    updatedBy: "admin",
  },
  {
    id: "2",
    code: "TPM-TEAM-002",
    name: "품질향상 분임조",
    description: "압축기 및 펌프 담당 TPM 분임조",
    department: "설비관리팀",
    leader: "user2",
    leaderName: "이관리",
    members: [
      {
        id: "5",
        userId: "user2",
        userName: "이관리",
        department: "설비관리팀",
        position: "팀장",
        role: "leader",
        joinDate: "2023-02-01",
        isActive: true,
      },
      {
        id: "6",
        userId: "user7",
        userName: "김기술",
        department: "정비2팀",
        position: "과장",
        role: "facilitator",
        joinDate: "2023-02-01",
        isActive: true,
      },
      {
        id: "7",
        userId: "user9",
        userName: "이전기",
        department: "전기팀",
        position: "대리",
        role: "secretary",
        joinDate: "2023-02-01",
        isActive: true,
      },
      {
        id: "8",
        userId: "user10",
        userName: "조기계",
        department: "기계팀",
        position: "사원",
        role: "member",
        joinDate: "2023-02-01",
        isActive: true,
      },
    ],
    equipmentArea: "B동 지하1층 유틸리티실",
    targetEquipments: ["2", "3"],
    establishedDate: "2023-02-01",
    status: "active",
    meetingDay: "수요일",
    meetingTime: "14:00",
    meetingLocation: "B동 회의실",
    isActive: true,
    createdAt: "2023-02-01T00:00:00Z",
    updatedAt: "2023-02-01T00:00:00Z",
    createdBy: "admin",
    updatedBy: "admin",
  },
  {
    id: "3",
    code: "TPM-TEAM-003",
    name: "로봇안전 분임조",
    description: "로봇 및 자동화 설비 담당 TPM 분임조",
    department: "생산2팀",
    leader: "user3",
    leaderName: "박운영",
    members: [
      {
        id: "9",
        userId: "user3",
        userName: "박운영",
        department: "생산2팀",
        position: "과장",
        role: "leader",
        joinDate: "2023-03-01",
        isActive: true,
      },
      {
        id: "10",
        userId: "user8",
        userName: "박수리",
        department: "정비1팀",
        position: "대리",
        role: "facilitator",
        joinDate: "2023-03-01",
        isActive: true,
      },
      {
        id: "11",
        userId: "user5",
        userName: "조안전",
        department: "안전환경팀",
        position: "과장",
        role: "secretary",
        joinDate: "2023-03-01",
        isActive: true,
      },
    ],
    equipmentArea: "C동 1층 로봇 작업구역",
    targetEquipments: ["4", "8"],
    establishedDate: "2023-03-01",
    status: "active",
    meetingDay: "금요일",
    meetingTime: "15:00",
    meetingLocation: "C동 회의실",
    isActive: true,
    createdAt: "2023-03-01T00:00:00Z",
    updatedAt: "2023-03-01T00:00:00Z",
    createdBy: "admin",
    updatedBy: "admin",
  },
]

export const mockTPMActivities: TPMActivity[] = [
  {
    id: "1",
    activityNo: "TPM-ACT-2024-001",
    title: "컨베이어 벨트 수명 연장 프로젝트",
    description: "컨베이어 벨트 마모 감소 및 수명 연장을 위한 개선 활동",
    teamId: "1",
    teamName: "설비개선 1팀",
    activityType: "focused",
    pillar: "개별개선",
    status: "completed",
    priority: "high",
    equipmentIds: ["1"],
    equipmentNames: ["컨베이어 #1"],
    location: "A동 1층",
    startDate: "2024-01-10",
    endDate: "2024-02-10",
    completionDate: "2024-02-08",
    completionRate: 100,
    goals: [
      {
        id: "1",
        title: "벨트 수명 연장",
        description: "컨베이어 벨트 교체 주기 연장",
        targetValue: 12,
        currentValue: 14,
        unit: "개월",
        achievementRate: 116.7,
      },
      {
        id: "2",
        title: "벨트 장력 균일화",
        description: "벨트 장력 편차 감소",
        targetValue: 5,
        currentValue: 3,
        unit: "%",
        achievementRate: 140,
      },
    ],
    activities: [
      {
        id: "1",
        step: 1,
        title: "현황 분석",
        description: "현재 벨트 마모 상태 및 원인 분석",
        assignedTo: "user1",
        assignedToName: "김생산",
        plannedStartDate: "2024-01-10",
        plannedEndDate: "2024-01-15",
        actualStartDate: "2024-01-10",
        actualEndDate: "2024-01-14",
        status: "completed",
        completionNotes: "마모 원인: 장력 불균형, 이물질 유입, 정렬 불량",
      },
      {
        id: "2",
        step: 2,
        title: "개선안 수립",
        description: "벨트 수명 연장을 위한 개선안 도출",
        assignedTo: "user6",
        assignedToName: "강정비",
        plannedStartDate: "2024-01-16",
        plannedEndDate: "2024-01-20",
        actualStartDate: "2024-01-15",
        actualEndDate: "2024-01-19",
        status: "completed",
        completionNotes: "자동 장력 조절 장치 설치, 이물질 제거 브러시 추가, 정렬 가이드 개선",
      },
      {
        id: "3",
        step: 3,
        title: "개선 실행",
        description: "도출된 개선안 실행",
        assignedTo: "user4",
        assignedToName: "정개선",
        plannedStartDate: "2024-01-21",
        plannedEndDate: "2024-01-31",
        actualStartDate: "2024-01-22",
        actualEndDate: "2024-02-01",
        status: "completed",
        completionNotes: "계획된 모든 개선 항목 구현 완료",
      },
      {
        id: "4",
        step: 4,
        title: "효과 검증",
        description: "개선 효과 측정 및 검증",
        assignedTo: "user3",
        assignedToName: "박운영",
        plannedStartDate: "2024-02-01",
        plannedEndDate: "2024-02-10",
        actualStartDate: "2024-02-02",
        actualEndDate: "2024-02-08",
        status: "completed",
        completionNotes: "벨트 마모율 40% 감소, 장력 균일도 향상",
      },
    ],
    results: {
      id: "1",
      summary: "컨베이어 벨트 수명 연장 프로젝트 성공적 완료",
      improvements: "자동 장력 조절 장치 설치, 이물질 제거 브러시 추가, 정렬 가이드 개선",
      beforeMetrics: {
        mtbf: 720,
        availability: 92,
        performance: 85,
        quality: 98,
        oee: 76.6,
      },
      afterMetrics: {
        mtbf: 960,
        availability: 96,
        performance: 90,
        quality: 99,
        oee: 85.5,
      },
      costSavings: 5000000,
      timeReduction: 24,
      qualityImprovement: 1,
      safetyImprovement: "벨트 파손으로 인한 안전사고 위험 감소",
      lessonsLearned: "정기적인 장력 점검의 중요성, 이물질 관리의 필요성",
      nextSteps: "다른 컨베이어 라인에도 동일한 개선 적용 확대",
    },
    isActive: true,
    createdAt: "2024-01-05T00:00:00Z",
    updatedAt: "2024-02-08T00:00:00Z",
    createdBy: "user1",
    updatedBy: "user1",
  },
  {
    id: "2",
    activityNo: "TPM-ACT-2024-002",
    title: "압축기 에너지 효율 향상 활동",
    description: "압축기 에너지 소비 절감을 위한 TPM 활동",
    teamId: "2",
    teamName: "품질향상 분임조",
    activityType: "quality",
    pillar: "품질보전",
    status: "in_progress",
    priority: "normal",
    equipmentIds: ["2"],
    equipmentNames: ["압축기 #1"],
    location: "B동 지하1층",
    startDate: "2024-02-01",
    endDate: "2024-03-15",
    completionRate: 60,
    goals: [
      {
        id: "3",
        title: "에너지 소비 절감",
        description: "압축기 전력 소비량 감소",
        targetValue: 15,
        currentValue: 10,
        unit: "%",
        achievementRate: 66.7,
      },
      {
        id: "4",
        title: "압축 효율 향상",
        description: "동일 출력 대비 압축 효율 향상",
        targetValue: 10,
        currentValue: 7,
        unit: "%",
        achievementRate: 70,
      },
    ],
    activities: [
      {
        id: "5",
        step: 1,
        title: "에너지 소비 분석",
        description: "현재 압축기 에너지 소비 패턴 분석",
        assignedTo: "user2",
        assignedToName: "이관리",
        plannedStartDate: "2024-02-01",
        plannedEndDate: "2024-02-10",
        actualStartDate: "2024-02-01",
        actualEndDate: "2024-02-09",
        status: "completed",
        completionNotes: "피크 시간대 과부하 운전, 공회전 시간 과다 발견",
      },
      {
        id: "6",
        step: 2,
        title: "누설 점검 및 개선",
        description: "압축 공기 누설 지점 파악 및 개선",
        assignedTo: "user7",
        assignedToName: "김기술",
        plannedStartDate: "2024-02-11",
        plannedEndDate: "2024-02-20",
        actualStartDate: "2024-02-10",
        actualEndDate: "2024-02-18",
        status: "completed",
        completionNotes: "총 12개 누설 지점 발견 및 수리 완료",
      },
      {
        id: "7",
        step: 3,
        title: "제어 시스템 최적화",
        description: "압축기 제어 로직 최적화",
        assignedTo: "user9",
        assignedToName: "이전기",
        plannedStartDate: "2024-02-21",
        plannedEndDate: "2024-03-05",
        actualStartDate: "2024-02-19",
        actualEndDate: "2024-03-01",
        status: "completed",
        completionNotes: "인버터 제어 방식 도입, 부하 감지 로직 개선",
      },
      {
        id: "8",
        step: 4,
        title: "효과 검증 및 표준화",
        description: "개선 효과 측정 및 표준 작업 수립",
        assignedTo: "user10",
        assignedToName: "조기계",
        plannedStartDate: "2024-03-06",
        plannedEndDate: "2024-03-15",
        plannedStartDate: "2024-03-02",
        status: "in_progress",
      },
    ],
    isActive: true,
    createdAt: "2024-01-25T00:00:00Z",
    updatedAt: "2024-03-01T00:00:00Z",
    createdBy: "user2",
    updatedBy: "user9",
  },
  {
    id: "3",
    activityNo: "TPM-ACT-2024-003",
    title: "로봇 안전 시스템 강화",
    description: "로봇 작업 구역 안전성 향상을 위한 TPM 활동",
    teamId: "3",
    teamName: "로봇안전 분임조",
    activityType: "safety",
    pillar: "안전환경",
    status: "planned",
    priority: "high",
    equipmentIds: ["4"],
    equipmentNames: ["로봇 #1"],
    location: "C동 1층",
    startDate: "2024-03-01",
    endDate: "2024-04-15",
    completionRate: 0,
    goals: [
      {
        id: "5",
        title: "안전사고 위험 감소",
        description: "로봇 관련 안전사고 위험 지수 감소",
        targetValue: 50,
        currentValue: 0,
        unit: "%",
        achievementRate: 0,
      },
      {
        id: "6",
        title: "안전 인터락 시스템 개선",
        description: "안전 인터락 반응 속도 개선",
        targetValue: 200,
        currentValue: 0,
        unit: "ms",
        achievementRate: 0,
      },
    ],
    activities: [
      {
        id: "9",
        step: 1,
        title: "위험성 평가",
        description: "로봇 작업 구역 위험성 평가 실시",
        assignedTo: "user5",
        assignedToName: "조안전",
        plannedStartDate: "2024-03-01",
        plannedEndDate: "2024-03-10",
        status: "planned",
      },
      {
        id: "10",
        step: 2,
        title: "안전 시스템 설계",
        description: "개선된 안전 시스템 설계",
        assignedTo: "user3",
        assignedToName: "박운영",
        plannedStartDate: "2024-03-11",
        plannedEndDate: "2024-03-25",
        status: "planned",
      },
      {
        id: "11",
        step: 3,
        title: "안전 장치 설치",
        description: "설계된 안전 장치 설치 및 구현",
        assignedTo: "user8",
        assignedToName: "박수리",
        plannedStartDate: "2024-03-26",
        plannedEndDate: "2024-04-05",
        status: "planned",
      },
      {
        id: "12",
        step: 4,
        title: "안전 교육 및 검증",
        description: "작업자 안전 교육 및 시스템 검증",
        assignedTo: "user5",
        assignedToName: "조안전",
        plannedStartDate: "2024-04-06",
        plannedEndDate: "2024-04-15",
        status: "planned",
      },
    ],
    isActive: true,
    createdAt: "2024-02-15T00:00:00Z",
    updatedAt: "2024-02-15T00:00:00Z",
    createdBy: "user3",
    updatedBy: "user3",
  },
]

export const tpmPillars = [
  { value: "자주보전", label: "자주보전" },
  { value: "계획보전", label: "계획보전" },
  { value: "품질보전", label: "품질보전" },
  { value: "개별개선", label: "개별개선" },
  { value: "초기관리", label: "초기관리" },
  { value: "교육훈련", label: "교육훈련" },
  { value: "안전환경", label: "안전환경" },
  { value: "사무TPM", label: "사무TPM" },
]

export const tpmActivityTypes = [
  { value: "autonomous", label: "자주보전 활동" },
  { value: "planned", label: "계획보전 활동" },
  { value: "quality", label: "품질보전 활동" },
  { value: "focused", label: "개별개선 활동" },
  { value: "early", label: "초기관리 활동" },
  { value: "training", label: "교육훈련 활동" },
  { value: "safety", label: "안전환경 활동" },
  { value: "office", label: "사무TPM 활동" },
]

export const tpmMemberRoles = [
  { value: "leader", label: "리더" },
  { value: "facilitator", label: "촉진자" },
  { value: "secretary", label: "간사" },
  { value: "member", label: "구성원" },
]
