export interface EquipmentType {
  id: string
  code: string
  name: string
  description?: string
  icon?: string
  properties: EquipmentProperty[]
  isActive: boolean
  createdAt: string
  updatedAt: string
  createdBy: string
  updatedBy: string
}

export interface EquipmentProperty {
  id: string
  code: string
  name: string
  description?: string
  dataType: "string" | "number" | "boolean" | "date" | "select" | "multiselect"
  required: boolean
  defaultValue?: string | number | boolean | Date | string[]
  options?: { label: string; value: string }[]
  unit?: string
  min?: number
  max?: number
  regex?: string
  order: number
  isActive: boolean
}

export interface EquipmentCategory {
  id: string
  code: string
  name: string
  parentId?: string
  level: number
  path: string
  description?: string
  isActive: boolean
  children?: EquipmentCategory[]
}

export interface EquipmentCodeRule {
  id: string
  name: string
  prefix: string
  separator: string
  segments: EquipmentCodeSegment[]
  example: string
  isActive: boolean
  appliedTo: string[] // 적용 대상 설비 유형 ID 목록
  description?: string
  createdAt: string
  updatedAt: string
}

export interface EquipmentCodeSegment {
  id: string
  type: "fixed" | "category" | "sequence" | "location" | "year" | "month" | "custom"
  value?: string
  length: number
  padChar?: string
  description?: string
}

export type EquipmentStatus = "active" | "inactive" | "maintenance" | "disposed"

export interface EquipmentMaster {
  id: string // Unique identifier for the master record
  equipmentId: string // User-facing equipment ID, potentially generated by rules
  equipmentName: string
  equipmentTypeId?: string // Foreign key to EquipmentType
  equipmentCategoryId?: string // Foreign key to EquipmentCategory
  model?: string
  manufacturer?: string
  serialNumber?: string
  installationDate: Date
  status: EquipmentStatus
  location?: string // Could be a structured location ID or free text
  department?: string
  description?: string
  purchaseDate?: Date
  purchasePrice?: number
  warrantyExpiryDate?: Date
  lastMaintenanceDate?: Date
  nextMaintenanceDate?: Date
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  customFields?: Record<string, any> // For dynamic properties based on EquipmentType
  photos?: string[] // URLs to equipment photos
  documents?: string[] // IDs or URLs to related documents
  qrCodeValue?: string // Value stored in the QR code for this equipment

  // Audit fields
  createdAt?: Date
  updatedAt?: Date
  createdBy?: string // User ID or name
  updatedBy?: string // User ID or name
}
