export interface Equipment {
  id: string;
  code: string;
  name: string;
  type: string;
  typeCode: string;
  model: string;
  manufacturer: string;
  serialNumber: string;
  location: string;
  locationId: string;
  department: string;
  departmentId: string;
  status: "running" | "stopped" | "maintenance" | "failure";
  priority: "critical" | "high" | "normal" | "low";
  installDate: string;
  warrantyEndDate?: string;
  lastMaintenanceDate?: string;
  nextMaintenanceDate?: string;
  specifications?: Record<string, any>;
  description?: string;
  isActive: boolean;
  createdAt: string;
  updatedAt: string;
  createdBy: string;
  updatedBy: string;
  photos?: EquipmentPhoto[];
  typeId: string; // 설비 유형 ID (마스터 연결)
  categoryId?: string; // 설비 분류 ID
  customProperties?: Record<string, any>; // 유형별 커스텀 속성값
  autoGeneratedCode?: boolean; // 코드 자동 생성 여부
}

export interface EquipmentFormData {
  code: string;
  name: string;
  typeCode: string;
  model: string;
  manufacturer: string;
  serialNumber: string;
  locationId: string;
  departmentId: string;
  status: "running" | "stopped" | "maintenance" | "failure";
  priority: "critical" | "high" | "normal" | "low";
  installDate: string;
  warrantyEndDate?: string;
  description?: string;
  specifications?: Record<string, any>;
  isActive: boolean;
  typeId: string; // 설비 유형 ID (마스터 연결)
  categoryId?: string; // 설비 분류 ID
  customProperties?: Record<string, any>; // 유형별 커스텀 속성값
  autoGeneratedCode?: boolean; // 코드 자동 생성 여부
}

export interface EquipmentFilter {
  type?: string;
  status?: string;
  priority?: string;
  location?: string;
  department?: string;
  searchTerm?: string;
}

export interface EquipmentPhoto {
  id: string;
  equipmentId: string;
  filename: string;
  originalName: string;
  url: string;
  type: "main" | "detail" | "manual" | "certificate";
  description?: string;
  uploadedAt: string;
  uploadedBy: string;
}
